using System;

namespace ShiftSoftware.ADP.Models.Part;

/// <summary>
/// Refers to a first receive date Part in a Stock (Warehouse), if provided separately
/// </summary>
[Docable]
public class StockPartFirstReceiveDateModel :
    IPartitionedItem,
    ICompanyProps,
    IIntegrationProps
{
    [DocIgnore]
    public string id { get; set; } = default!;

    /// <summary>
    /// The Unique Part Number
    /// </summary>
    public string PartNumber { get; set; }

    /// <summary>
    /// The Warehouse/Location Identifier where the part is stored.
    /// </summary>
    public string Location { get; set; } = default!;

    public DateTimeOffset? FirstReceivedDate { get; set; }

    [DocIgnore]
    public string ItemType => ModelTypes.StockPartFirstReceiveDate;

    [DocIgnore]
    public long? CompanyID { get; set; }

    /// <summary>
    /// The Company Hash ID from the Identity System.
    /// </summary>
    public string CompanyHashID { get; set; }


    /// <summary>
    /// An External Identifier that can be used for system to system Integration
    /// </summary>
    public string IntegrationID { get; set; }


    /// <summary>
    /// A Unique key generated by ADP and used to ensure that repeated external posting of the same entry does not result in duplicate records.
    /// </summary>
    public Guid? IdempotencyKey { get; set; }


    /// <summary>
    /// A boolean flag indicating the completion of system to system Integration
    /// </summary>
    public bool IntegrationSuccessStatus { get; set; }
}