trigger:
 tags:
    include:
    - release-nuget-*

pool:
  vmImage: ubuntu-22.04
  
variables:
- group: pipeline

steps:

 - checkout: self
   submodules: true
   persistCredentials: true

 - script: dotnet build --configuration release
   displayName: 'Build All Projects'

 - script: dotnet pack ADP.Models/Models --configuration Release --output $(Build.ArtifactStagingDirectory)/ADP
   condition: or(contains(variables['Build.SourceBranch'], 'refs/tags/release-all'), contains(variables['Build.SourceBranch'], 'refs/tags/release-nuget')) 
   displayName: 'pack ADP.Models'

 - script: dotnet pack ADP.LookupServices/Lookup.Services --configuration Release --output $(Build.ArtifactStagingDirectory)/ADP
   condition: or(contains(variables['Build.SourceBranch'], 'refs/tags/release-all'), contains(variables['Build.SourceBranch'], 'refs/tags/release-nuget')) 
   displayName: 'pack ADP.LookupServices'

 - script: dotnet pack ADP.SyncAgent/SyncAgent --configuration Release --output $(Build.ArtifactStagingDirectory)/ADP
   condition: or(contains(variables['Build.SourceBranch'], 'refs/tags/release-all'), contains(variables['Build.SourceBranch'], 'refs/tags/release-nuget')) 
   displayName: 'pack ADP.SyncAgent'


 - script: dotnet test ADP.LookupServices.BDD
   displayName: 'ADP.LookupServices BDD Tests'


 - task: NuGetToolInstaller@1
   inputs:
    versionSpec: '6.9.1'

 - task: NuGetCommand@2
   displayName: 'Push ADP Packages'
   condition: or(contains(variables['Build.SourceBranch'], 'refs/tags/release-all'), contains(variables['Build.SourceBranch'], 'refs/tags/release-nuget'))
   inputs:
    command: 'custom'
    arguments: 'push "$(Build.ArtifactStagingDirectory)/ADP/**/*.nupkg" -Source https://api.nuget.org/v3/index.json -ApiKey $(ShiftSoftwareNugetApiKey)'