namespace ShiftSoftware.ADP.Darlastic.Engine;

/// <summary>
/// Which rules participated in a pair's score. Set as cheap bit-ors on the SAME code path that
/// computes the score (RealMatcher.ScoreCore), so flag truth can never drift from score truth.
/// The case browser's category index is built from these during the cluster walk — no trace
/// allocation in the 12.4M-pair hot loop.
/// </summary>
[Flags]
public enum MatchFlags
{
    None = 0,
    NamesBoth        = 1 << 0,
    PhonesBoth       = 1 << 1,
    PhoneExact       = 1 << 2,
    PhoneSuffix      = 1 << 3,   // weak↔strong suffix-8 bridge
    IdsBoth          = 1 << 4,
    IdEqual          = 1 << 5,
    IdConflict       = 1 << 6,   // ×0.3 fired
    NameOnlyDamp     = 1 << 7,   // ×0.70 fired (name is the only signal)
    NameConsistent   = 1 << 8,   // exact phone + per-token-aligned names → 0.93 floor fired
    NameConflictCap  = 1 << 9,   // exact phone + unrelated names → 0.55 cap fired
    AddressBoost     = 1 << 10,  // district-level address agreement → +0.05 fired
    ChainSliceRescue = 1 << 11,  // same given + exact phone + district remainder → raised to 0.91
    DobEqual         = 1 << 12,  // +0.05 fired
    DobConflict      = 1 << 13,  // ×0.6 fired
    PhoneNameMerge   = 1 << 14,  // exact phone + overlapping (not fully consistent) name, no gender/total conflict → 0.91 (name-chain-slice rule)
    GenderConflict   = 1 << 15,  // exact phone but male vs female → capped (spouses/family on one line)
    VinBoth          = 1 << 16,  // both sides carry ≥1 VIN link (a comparison was possible)
    VinSoldOverlap   = 1 << 17,  // shared VIN, ≥1 sale side, ownership periods consistent — strong ownership key
    VinServiced      = 1 << 18,  // shared VIN, service-only on both sides — corroboration grade
    VinTransfer      = 1 << 19,  // shared VIN but disjoint periods with a sale between — ownership changed, NOT a merge signal (P7)
    VinSoldMerge     = 1 << 20,  // sold-overlap floor fired → 0.91 auto-merge (names not in hard conflict)
    OrgLine          = 1 << 21,  // exact phone + a business/placeholder name (Company/Stock/Parts/…) — person-merge floor withheld (NOT a veto; identical org names still merge on the base)
    SameAsRef        = 1 << 22,  // one side carries a source-asserted reference to the other (explicit FK, e.g. ticket → DMS customer key)
    SameAsMerge      = 1 << 23,  // same-as floor fired → auto-merge (names consistent/aligned or absent)
}

/// <summary>One step of a pair's scoring story, in engine execution order.</summary>
/// <param name="Stage">Machine key the UI maps to a station: signal | base | gate | address | conflict | decide.</param>
/// <param name="Title">Short human label ("Name similarity", "Chain-slice rescue").</param>
/// <param name="Detail">The numbers ("trigram 0.42 · JW 0.78 → blend 0.60 × weight 0.45").</param>
/// <param name="ConfAfter">Running confidence after this step, when it changed or concluded a phase.</param>
public sealed record TraceStep(string Stage, string Title, string Detail, double? ConfAfter = null);

/// <summary>
/// Trace sink for explain-mode scoring. Passed as null in every hot path (zero overhead);
/// allocated only when the case browser explains ONE pair on demand. The trace is generated by
/// the live scorer itself — the single-source-of-truth principle of `dotnet run eval` extended
/// to explanations: the browser can never claim something the engine didn't do.
/// </summary>
public sealed class MatchTrace
{
    public readonly List<TraceStep> Steps = [];
    public void Add(string stage, string title, string detail, double? confAfter = null)
        => Steps.Add(new TraceStep(stage, title, detail, confAfter));
}
