export type vehicleServiceItemDTO = {
  group: {
    name?: string;
    tabOrder?: number;
    isDefault?: boolean;
    isSequential?: boolean;
  };
  showDocumentUploader?: boolean;
  documentUploaderIsRequired: boolean;
  name: string;
  description: string;
  title: string;
  image: string;
  type: string;
  typeEnum: 'free' | 'paid';
  activatedAt: string;
  expiresAt?: string;
  status: string;
  statusEnum: 'processed' | 'expired' | 'pending' | 'cancelled' | 'activationRequired';
  campaignID?: number;
  campaignUniqueReference: string;
  packageCode: string;
  cost?: number;
  claimDate?: string;
  modelCostID?: number;
  serviceItemID: number;
  paidServiceInvoiceLineID?: number;
  companyID: string;
  companyName: string;
  invoiceNumber: string;
  jobNumber: string;
  maximumMileage?: number;
  claimable: boolean;
  claimingMethodEnum: 'claimByScanningQRCode' | 'claimByEnteringInvoiceAndJobNumber';
  vehicleInspectionID: string;
  signature: string;
  signatureExpiry: string;
};
