// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace LookupServices.BDD.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ServiceItemResolversCompanyNamePrintURLFeature : object, Xunit.IClassFixture<ServiceItemResolversCompanyNamePrintURLFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Xunit.ITestOutputHelper _testOutputHelper;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Service Item Resolvers — Company Name & Print URL", @"  LookupOptions resolvers enrich service items with external data.
  When a claim has a non-zero CompanyID, the CompanyNameResolver is
  called to populate CompanyName. For print URLs, the Vehicle-Inspection
  resolver applies to items with a VehicleInspectionID, but if a
  VehicleServiceActivation is present and the ServiceActivation resolver
  is configured, it takes priority and overrides the inspection URL.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "ServiceItems_Resolvers.feature"
#line hidden
        
        public ServiceItemResolversCompanyNamePrintURLFeature(ServiceItemResolversCompanyNamePrintURLFeature.FixtureData fixtureData, Xunit.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/ServiceItems_Resolvers.feature.ndjson", 4);
        }
        
        async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Processed item enriches its company name via the resolver")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Service Item Resolvers — Company Name & Print URL")]
        [global::Xunit.TraitAttribute("Description", "Processed item enriches its company name via the resolver")]
        public async global::System.Threading.Tasks.Task ProcessedItemEnrichesItsCompanyNameViaTheResolver()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Processed item enriches its company name via the resolver", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 9
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table97 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "InvoiceDate",
                            "CompanyID",
                            "BranchID",
                            "BrandID"});
                table97.AddRow(new string[] {
                            "1FDKF37GXVEB34368",
                            "2026-01-15",
                            "1",
                            "10",
                            "1"});
#line 10
  await testRunner.GivenAsync("vehicles in dealer stock:", ((string)(null)), table97, "Given ");
#line hidden
                global::Reqnroll.Table table98 = new global::Reqnroll.Table(new string[] {
                            "ServiceItemID",
                            "Name",
                            "BrandID",
                            "ActiveForMonths",
                            "MaximumMileage"});
                table98.AddRow(new string[] {
                            "SI-001",
                            "Oil Change",
                            "1",
                            "24",
                            "10000"});
#line 13
  await testRunner.AndAsync("service items:", ((string)(null)), table98, "And ");
#line hidden
                global::Reqnroll.Table table99 = new global::Reqnroll.Table(new string[] {
                            "ServiceItemID",
                            "ClaimDate",
                            "JobNumber",
                            "InvoiceNumber",
                            "CompanyID"});
                table99.AddRow(new string[] {
                            "SI-001",
                            "2026-06-01",
                            "JOB-001",
                            "INV-001",
                            "1"});
#line 16
  await testRunner.AndAsync("item claims:", ((string)(null)), table99, "And ");
#line hidden
#line 19
  await testRunner.AndAsync("company 1 is named \"Toyota Motors\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
  await testRunner.AndAsync("the free service start date is \"2026-01-15\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
  await testRunner.WhenAsync("evaluating service items for \"1FDKF37GXVEB34368\" with language \"en\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 22
  await testRunner.ThenAsync("service item \"SI-001\" has status \"processed\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 23
  await testRunner.AndAsync("service item \"SI-001\" has company name \"Toyota Motors\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Service activation print URL overrides the inspection print URL")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Service Item Resolvers — Company Name & Print URL")]
        [global::Xunit.TraitAttribute("Description", "Service activation print URL overrides the inspection print URL")]
        public async global::System.Threading.Tasks.Task ServiceActivationPrintURLOverridesTheInspectionPrintURL()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Service activation print URL overrides the inspection print URL", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 25
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table100 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "InvoiceDate",
                            "CompanyID",
                            "BranchID",
                            "BrandID"});
                table100.AddRow(new string[] {
                            "1FDKF37GXVEB34368",
                            "2026-01-15",
                            "1",
                            "10",
                            "1"});
#line 26
  await testRunner.GivenAsync("vehicles in dealer stock:", ((string)(null)), table100, "Given ");
#line hidden
                global::Reqnroll.Table table101 = new global::Reqnroll.Table(new string[] {
                            "ServiceItemID",
                            "Name",
                            "BrandID",
                            "ActivationTrigger",
                            "ActivationType",
                            "VehicleInspectionTypeID",
                            "ActiveForMonths"});
                table101.AddRow(new string[] {
                            "SI-INSP",
                            "Inspection",
                            "1",
                            "VehicleInspection",
                            "FirstTriggerOnly",
                            "7",
                            "12"});
#line 29
  await testRunner.AndAsync("service items:", ((string)(null)), table101, "And ");
#line hidden
                global::Reqnroll.Table table102 = new global::Reqnroll.Table(new string[] {
                            "id",
                            "InspectionDate",
                            "VehicleInspectionTypeID"});
                table102.AddRow(new string[] {
                            "INSP-A",
                            "2026-02-01",
                            "7"});
#line 32
  await testRunner.AndAsync("vehicle inspections:", ((string)(null)), table102, "And ");
#line hidden
                global::Reqnroll.Table table103 = new global::Reqnroll.Table(new string[] {
                            "id",
                            "WarrantyActivationDate"});
                table103.AddRow(new string[] {
                            "ACT-1",
                            "2026-01-15"});
#line 35
  await testRunner.AndAsync("vehicle service activations:", ((string)(null)), table103, "And ");
#line hidden
#line 38
  await testRunner.AndAsync("an inspection pre-claim voucher URL resolver is configured", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
  await testRunner.AndAsync("a service activation pre-claim voucher URL resolver is configured", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
  await testRunner.WhenAsync("evaluating service items for \"1FDKF37GXVEB34368\" with language \"en\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 41
  await testRunner.ThenAsync("service item \"SI-INSP\" has print url \"activation/ACT-1/SI-INSP\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ServiceItemResolversCompanyNamePrintURLFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
            {
                await ServiceItemResolversCompanyNamePrintURLFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
