// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace LookupServices.BDD.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class IneligibleServiceItemsWithExistingClaimsFeature : object, Xunit.IClassFixture<IneligibleServiceItemsWithExistingClaimsFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Xunit.ITestOutputHelper _testOutputHelper;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Ineligible Service Items with Existing Claims", @"  When a vehicle has a claim for a service item that is no longer
  in the vehicle's current eligible list (for example, because a
  brand filter excludes it), the evaluator still surfaces it as a
  Processed item so the claim history is visible. Its claim fields
  (ClaimDate, JobNumber, InvoiceNumber, PackageCode) come from the
  claim itself, not from the service item.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "ServiceItems_Ineligible.feature"
#line hidden
        
        public IneligibleServiceItemsWithExistingClaimsFeature(IneligibleServiceItemsWithExistingClaimsFeature.FixtureData fixtureData, Xunit.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/ServiceItems_Ineligible.feature.ndjson", 4);
        }
        
        async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Claimed item that is no longer eligible surfaces as processed with claim details")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Ineligible Service Items with Existing Claims")]
        [global::Xunit.TraitAttribute("Description", "Claimed item that is no longer eligible surfaces as processed with claim details")]
        public async global::System.Threading.Tasks.Task ClaimedItemThatIsNoLongerEligibleSurfacesAsProcessedWithClaimDetails()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Claimed item that is no longer eligible surfaces as processed with claim details", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 9
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table67 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "InvoiceDate",
                            "CompanyID",
                            "BranchID",
                            "BrandID"});
                table67.AddRow(new string[] {
                            "1FDKF37GXVEB34368",
                            "2026-01-15",
                            "1",
                            "10",
                            "1"});
#line 10
  await testRunner.GivenAsync("vehicles in dealer stock:", ((string)(null)), table67, "Given ");
#line hidden
                global::Reqnroll.Table table68 = new global::Reqnroll.Table(new string[] {
                            "ServiceItemID",
                            "Name",
                            "BrandID",
                            "ActiveForMonths"});
                table68.AddRow(new string[] {
                            "SI-OLDOIL",
                            "Old Oil Svc",
                            "99",
                            "24"});
#line 13
  await testRunner.AndAsync("service items:", ((string)(null)), table68, "And ");
#line hidden
                global::Reqnroll.Table table69 = new global::Reqnroll.Table(new string[] {
                            "ServiceItemID",
                            "ClaimDate",
                            "JobNumber",
                            "InvoiceNumber"});
                table69.AddRow(new string[] {
                            "SI-OLDOIL",
                            "2025-08-01",
                            "JOB-OLD",
                            "INV-OLD"});
#line 16
  await testRunner.AndAsync("item claims:", ((string)(null)), table69, "And ");
#line hidden
#line 19
  await testRunner.AndAsync("the free service start date is \"2026-01-15\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
  await testRunner.WhenAsync("evaluating service items for \"1FDKF37GXVEB34368\" with language \"en\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 21
  await testRunner.ThenAsync("service item \"SI-OLDOIL\" has status \"processed\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 22
  await testRunner.AndAsync("service item \"SI-OLDOIL\" has job number \"JOB-OLD\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
  await testRunner.AndAsync("service item \"SI-OLDOIL\" has invoice number \"INV-OLD\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Ineligible processed item carries the package code from the claim")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Ineligible Service Items with Existing Claims")]
        [global::Xunit.TraitAttribute("Description", "Ineligible processed item carries the package code from the claim")]
        public async global::System.Threading.Tasks.Task IneligibleProcessedItemCarriesThePackageCodeFromTheClaim()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Ineligible processed item carries the package code from the claim", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 25
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table70 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "InvoiceDate",
                            "CompanyID",
                            "BranchID",
                            "BrandID"});
                table70.AddRow(new string[] {
                            "1FDKF37GXVEB34368",
                            "2026-01-15",
                            "1",
                            "10",
                            "1"});
#line 26
  await testRunner.GivenAsync("vehicles in dealer stock:", ((string)(null)), table70, "Given ");
#line hidden
                global::Reqnroll.Table table71 = new global::Reqnroll.Table(new string[] {
                            "ServiceItemID",
                            "Name",
                            "BrandID",
                            "ActiveForMonths"});
                table71.AddRow(new string[] {
                            "SI-OLDOIL",
                            "Old Oil Svc",
                            "99",
                            "24"});
#line 29
  await testRunner.AndAsync("service items:", ((string)(null)), table71, "And ");
#line hidden
                global::Reqnroll.Table table72 = new global::Reqnroll.Table(new string[] {
                            "ServiceItemID",
                            "ClaimDate",
                            "JobNumber",
                            "InvoiceNumber",
                            "PackageCode"});
                table72.AddRow(new string[] {
                            "SI-OLDOIL",
                            "2025-08-01",
                            "JOB-OLD",
                            "INV-OLD",
                            "PKG-CLAIM"});
#line 32
  await testRunner.AndAsync("item claims:", ((string)(null)), table72, "And ");
#line hidden
#line 35
  await testRunner.AndAsync("the free service start date is \"2026-01-15\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
  await testRunner.WhenAsync("evaluating service items for \"1FDKF37GXVEB34368\" with language \"en\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 37
  await testRunner.ThenAsync("service item \"SI-OLDOIL\" has package code \"PKG-CLAIM\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
            {
                await IneligibleServiceItemsWithExistingClaimsFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
            {
                await IneligibleServiceItemsWithExistingClaimsFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
