// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace LookupServices.BDD.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ServiceItemProgramRolesAndBaseScheduleCapFeature : object, Xunit.IClassFixture<ServiceItemProgramRolesAndBaseScheduleCapFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Xunit.ITestOutputHelper _testOutputHelper;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Service Item Program Roles and Base Schedule Cap", @"  A catalog item's program role controls only whether it can define the base
  scheduled-service mileage cap. Reward items remain ordinary free service
  items for ordering, rolling expiry, status, cancellation, warnings, signing,
  VIN exclusion, and claimed-item recovery.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "ServiceItems_ProgramRole.feature"
#line hidden
        
        public ServiceItemProgramRolesAndBaseScheduleCapFeature(ServiceItemProgramRolesAndBaseScheduleCapFeature.FixtureData fixtureData, Xunit.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/ServiceItems_ProgramRole.feature.ndjson", 23);
        }
        
        async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.TheoryAttribute(DisplayName="Reward tiers require their vehicle\'s base schedule cap and latest paid-service hi" +
            "story")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Service Item Program Roles and Base Schedule Cap")]
        [global::Xunit.TraitAttribute("Description", "Reward tiers require their vehicle\'s base schedule cap and latest paid-service hi" +
            "story")]
        [global::Xunit.InlineDataAttribute("40000", "55000", "45000", "50000", "0", new string[0])]
        [global::Xunit.InlineDataAttribute("60000", "75000", "65000", "70000", "1", new string[0])]
        [global::Xunit.InlineDataAttribute("80000", "95000", "85000", "90000", "2", new string[0])]
        public async global::System.Threading.Tasks.Task RewardTiersRequireTheirVehiclesBaseScheduleCapAndLatestPaid_ServiceHistory(string baseCap, string rewardMileage, string previousA, string previousB, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("BaseCap", baseCap);
            argumentsOfScenario.Add("RewardMileage", rewardMileage);
            argumentsOfScenario.Add("PreviousA", previousA);
            argumentsOfScenario.Add("PreviousB", previousB);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Reward tiers require their vehicle\'s base schedule cap and latest paid-service hi" +
                    "story", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table382 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "InvoiceDate",
                            "CompanyID",
                            "BranchID",
                            "BrandID"});
                table382.AddRow(new string[] {
                            "1FDKF37GXVEB34368",
                            "2026-01-15",
                            "1",
                            "10",
                            "1"});
#line 8
  await testRunner.GivenAsync("vehicles in dealer stock:", ((string)(null)), table382, "Given ");
#line hidden
                global::Reqnroll.Table table383 = new global::Reqnroll.Table(new string[] {
                            "ServiceItemID",
                            "Name",
                            "BrandID",
                            "ActiveForMonths",
                            "MaximumMileage",
                            "ProgramRole"});
                table383.AddRow(new string[] {
                            "SI-BASE",
                            "Base schedule end",
                            "1",
                            "6",
                            string.Format("{0}", baseCap),
                            ""});
                table383.AddRow(new string[] {
                            "SI-REWARD",
                            "Mileage reward",
                            "1",
                            "3",
                            string.Format("{0}", rewardMileage),
                            "Reward"});
#line 11
  await testRunner.AndAsync("service items:", ((string)(null)), table383, "And ");
#line hidden
                global::Reqnroll.Table table384 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Operator",
                            "Selection",
                            "Count",
                            "Values"});
                table384.AddRow(new string[] {
                            "serviceItems.baseSchedule.maximumMileage",
                            "Equals",
                            "",
                            "",
                            string.Format("{0}", baseCap)});
                table384.AddRow(new string[] {
                            "serviceHistory.laborLines.packageCode",
                            "ContainsAll",
                            "Latest",
                            "2",
                            string.Format("{0},{1}", previousA, previousB)});
#line 15
  await testRunner.AndAsync("service item \"SI-REWARD\" has eligibility conditions:", ((string)(null)), table384, "And ");
#line hidden
                global::Reqnroll.Table table385 = new global::Reqnroll.Table(new string[] {
                            "CompanyID",
                            "BranchID",
                            "InvoiceNumber",
                            "OrderDocumentNumber",
                            "InvoiceDate",
                            "PackageCode"});
                table385.AddRow(new string[] {
                            "1",
                            "10",
                            "INV-A",
                            "JOB-A",
                            "2026-02-01",
                            string.Format("{0}", previousA)});
                table385.AddRow(new string[] {
                            "1",
                            "10",
                            "INV-B",
                            "JOB-B",
                            "2026-03-01",
                            string.Format("{0}", previousB)});
#line 19
  await testRunner.AndAsync("labor lines:", ((string)(null)), table385, "And ");
#line hidden
#line 23
  await testRunner.AndAsync("the free service start date is \"2026-01-15\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
  await testRunner.WhenAsync("evaluating service items for \"1FDKF37GXVEB34368\" with language \"en\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 25
  await testRunner.ThenAsync("service item \"SI-REWARD\" is in the result", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="A reward is excluded when its configured base cap is wrong")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Service Item Program Roles and Base Schedule Cap")]
        [global::Xunit.TraitAttribute("Description", "A reward is excluded when its configured base cap is wrong")]
        public async global::System.Threading.Tasks.Task ARewardIsExcludedWhenItsConfiguredBaseCapIsWrong()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A reward is excluded when its configured base cap is wrong", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 33
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table386 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "InvoiceDate",
                            "CompanyID",
                            "BranchID",
                            "BrandID"});
                table386.AddRow(new string[] {
                            "1FDKF37GXVEB34368",
                            "2026-01-15",
                            "1",
                            "10",
                            "1"});
#line 34
  await testRunner.GivenAsync("vehicles in dealer stock:", ((string)(null)), table386, "Given ");
#line hidden
                global::Reqnroll.Table table387 = new global::Reqnroll.Table(new string[] {
                            "ServiceItemID",
                            "Name",
                            "BrandID",
                            "ActiveForMonths",
                            "MaximumMileage",
                            "ProgramRole"});
                table387.AddRow(new string[] {
                            "SI-BASE",
                            "Base schedule end",
                            "1",
                            "6",
                            "40000",
                            ""});
                table387.AddRow(new string[] {
                            "SI-REWARD",
                            "Mileage reward",
                            "1",
                            "3",
                            "55000",
                            "Reward"});
#line 37
  await testRunner.AndAsync("service items:", ((string)(null)), table387, "And ");
#line hidden
                global::Reqnroll.Table table388 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Operator",
                            "Values"});
                table388.AddRow(new string[] {
                            "serviceItems.baseSchedule.maximumMileage",
                            "Equals",
                            "60000"});
#line 41
  await testRunner.AndAsync("service item \"SI-REWARD\" has eligibility conditions:", ((string)(null)), table388, "And ");
#line hidden
#line 44
  await testRunner.AndAsync("the free service start date is \"2026-01-15\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 45
  await testRunner.WhenAsync("evaluating service items for \"1FDKF37GXVEB34368\" with language \"en\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 46
  await testRunner.ThenAsync("service item \"SI-REWARD\" is not in the result", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="A reward is excluded when no base schedule cap exists")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Service Item Program Roles and Base Schedule Cap")]
        [global::Xunit.TraitAttribute("Description", "A reward is excluded when no base schedule cap exists")]
        public async global::System.Threading.Tasks.Task ARewardIsExcludedWhenNoBaseScheduleCapExists()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A reward is excluded when no base schedule cap exists", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 48
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table389 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "InvoiceDate",
                            "CompanyID",
                            "BranchID",
                            "BrandID"});
                table389.AddRow(new string[] {
                            "1FDKF37GXVEB34368",
                            "2026-01-15",
                            "1",
                            "10",
                            "1"});
#line 49
  await testRunner.GivenAsync("vehicles in dealer stock:", ((string)(null)), table389, "Given ");
#line hidden
                global::Reqnroll.Table table390 = new global::Reqnroll.Table(new string[] {
                            "ServiceItemID",
                            "Name",
                            "BrandID",
                            "ActiveForMonths",
                            "MaximumMileage",
                            "ProgramRole"});
                table390.AddRow(new string[] {
                            "SI-REWARD",
                            "Mileage reward",
                            "1",
                            "3",
                            "55000",
                            "Reward"});
#line 52
  await testRunner.AndAsync("service items:", ((string)(null)), table390, "And ");
#line hidden
                global::Reqnroll.Table table391 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Operator",
                            "Values"});
                table391.AddRow(new string[] {
                            "serviceItems.baseSchedule.maximumMileage",
                            "Equals",
                            "40000"});
#line 55
  await testRunner.AndAsync("service item \"SI-REWARD\" has eligibility conditions:", ((string)(null)), table391, "And ");
#line hidden
#line 58
  await testRunner.AndAsync("the free service start date is \"2026-01-15\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 59
  await testRunner.WhenAsync("evaluating service items for \"1FDKF37GXVEB34368\" with language \"en\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 60
  await testRunner.ThenAsync("service item \"SI-REWARD\" is not in the result", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Missing required service history excludes a reward even when the cap matches")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Service Item Program Roles and Base Schedule Cap")]
        [global::Xunit.TraitAttribute("Description", "Missing required service history excludes a reward even when the cap matches")]
        public async global::System.Threading.Tasks.Task MissingRequiredServiceHistoryExcludesARewardEvenWhenTheCapMatches()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Missing required service history excludes a reward even when the cap matches", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 62
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table392 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "InvoiceDate",
                            "CompanyID",
                            "BranchID",
                            "BrandID"});
                table392.AddRow(new string[] {
                            "1FDKF37GXVEB34368",
                            "2026-01-15",
                            "1",
                            "10",
                            "1"});
#line 63
  await testRunner.GivenAsync("vehicles in dealer stock:", ((string)(null)), table392, "Given ");
#line hidden
                global::Reqnroll.Table table393 = new global::Reqnroll.Table(new string[] {
                            "ServiceItemID",
                            "Name",
                            "BrandID",
                            "ActiveForMonths",
                            "MaximumMileage",
                            "ProgramRole"});
                table393.AddRow(new string[] {
                            "SI-BASE",
                            "Base schedule end",
                            "1",
                            "6",
                            "40000",
                            ""});
                table393.AddRow(new string[] {
                            "SI-REWARD",
                            "Mileage reward",
                            "1",
                            "3",
                            "55000",
                            "Reward"});
#line 66
  await testRunner.AndAsync("service items:", ((string)(null)), table393, "And ");
#line hidden
                global::Reqnroll.Table table394 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Operator",
                            "Selection",
                            "Count",
                            "Values"});
                table394.AddRow(new string[] {
                            "serviceItems.baseSchedule.maximumMileage",
                            "Equals",
                            "",
                            "",
                            "40000"});
                table394.AddRow(new string[] {
                            "serviceHistory.laborLines.packageCode",
                            "ContainsAll",
                            "Latest",
                            "2",
                            "45000,50000"});
#line 70
  await testRunner.AndAsync("service item \"SI-REWARD\" has eligibility conditions:", ((string)(null)), table394, "And ");
#line hidden
                global::Reqnroll.Table table395 = new global::Reqnroll.Table(new string[] {
                            "CompanyID",
                            "BranchID",
                            "InvoiceNumber",
                            "OrderDocumentNumber",
                            "InvoiceDate",
                            "PackageCode"});
                table395.AddRow(new string[] {
                            "1",
                            "10",
                            "INV-045",
                            "JOB-045",
                            "2026-02-01",
                            "45000"});
#line 74
  await testRunner.AndAsync("labor lines:", ((string)(null)), table395, "And ");
#line hidden
#line 77
  await testRunner.AndAsync("the free service start date is \"2026-01-15\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 78
  await testRunner.WhenAsync("evaluating service items for \"1FDKF37GXVEB34368\" with language \"en\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 79
  await testRunner.ThenAsync("service item \"SI-REWARD\" is not in the result", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Static catalog filters are applied before base schedule cap membership")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Service Item Program Roles and Base Schedule Cap")]
        [global::Xunit.TraitAttribute("Description", "Static catalog filters are applied before base schedule cap membership")]
        public async global::System.Threading.Tasks.Task StaticCatalogFiltersAreAppliedBeforeBaseScheduleCapMembership()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Static catalog filters are applied before base schedule cap membership", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 81
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table396 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "InvoiceDate",
                            "CompanyID",
                            "BranchID",
                            "BrandID",
                            "CountryID",
                            "Katashiki"});
                table396.AddRow(new string[] {
                            "1FDKF37GXVEB34368",
                            "2026-01-15",
                            "1",
                            "10",
                            "1",
                            "42",
                            "ABC123"});
#line 82
  await testRunner.GivenAsync("vehicles in dealer stock:", ((string)(null)), table396, "Given ");
#line hidden
                global::Reqnroll.Table table397 = new global::Reqnroll.Table(new string[] {
                            "ServiceItemID",
                            "Name",
                            "BrandID",
                            "CompanyID",
                            "CountryID",
                            "CampaignStartDate",
                            "CampaignEndDate",
                            "ModelCostKatashiki",
                            "IsDeleted",
                            "ActiveForMonths",
                            "MaximumMileage",
                            "ProgramRole"});
                table397.AddRow(new string[] {
                            "SI-BASE",
                            "Base schedule end",
                            "1",
                            "1",
                            "42",
                            "",
                            "",
                            "",
                            "false",
                            "6",
                            "40000",
                            ""});
                table397.AddRow(new string[] {
                            "SI-DELETED",
                            "Deleted schedule",
                            "1",
                            "1",
                            "42",
                            "",
                            "",
                            "",
                            "true",
                            "6",
                            "99000",
                            ""});
                table397.AddRow(new string[] {
                            "SI-BRAND",
                            "Other brand",
                            "2",
                            "1",
                            "42",
                            "",
                            "",
                            "",
                            "false",
                            "6",
                            "98000",
                            ""});
                table397.AddRow(new string[] {
                            "SI-COMPANY",
                            "Other company",
                            "1",
                            "99",
                            "42",
                            "",
                            "",
                            "",
                            "false",
                            "6",
                            "97000",
                            ""});
                table397.AddRow(new string[] {
                            "SI-COUNTRY",
                            "Other country",
                            "1",
                            "1",
                            "99",
                            "",
                            "",
                            "",
                            "false",
                            "6",
                            "96000",
                            ""});
                table397.AddRow(new string[] {
                            "SI-WINDOW",
                            "Old campaign",
                            "1",
                            "1",
                            "42",
                            "2020-01-01",
                            "2020-12-31",
                            "",
                            "false",
                            "6",
                            "95000",
                            ""});
                table397.AddRow(new string[] {
                            "SI-MODEL",
                            "Other vehicle model",
                            "1",
                            "1",
                            "42",
                            "",
                            "",
                            "ZZZ",
                            "false",
                            "6",
                            "94000",
                            ""});
                table397.AddRow(new string[] {
                            "SI-REWARD",
                            "Mileage reward",
                            "1",
                            "1",
                            "42",
                            "",
                            "",
                            "",
                            "false",
                            "3",
                            "55000",
                            "Reward"});
#line 85
  await testRunner.AndAsync("service items:", ((string)(null)), table397, "And ");
#line hidden
                global::Reqnroll.Table table398 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Operator",
                            "Values"});
                table398.AddRow(new string[] {
                            "serviceItems.baseSchedule.maximumMileage",
                            "Equals",
                            "40000"});
#line 95
  await testRunner.AndAsync("service item \"SI-REWARD\" has eligibility conditions:", ((string)(null)), table398, "And ");
#line hidden
#line 98
  await testRunner.AndAsync("the free service start date is \"2026-01-15\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 99
  await testRunner.WhenAsync("evaluating service items for \"1FDKF37GXVEB34368\" with language \"en\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 100
  await testRunner.ThenAsync("service item \"SI-REWARD\" is in the result", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="A scheduled item contributes to the cap before its own custom conditions are eval" +
            "uated")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Service Item Program Roles and Base Schedule Cap")]
        [global::Xunit.TraitAttribute("Description", "A scheduled item contributes to the cap before its own custom conditions are eval" +
            "uated")]
        public async global::System.Threading.Tasks.Task AScheduledItemContributesToTheCapBeforeItsOwnCustomConditionsAreEvaluated()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A scheduled item contributes to the cap before its own custom conditions are eval" +
                    "uated", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 102
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table399 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "InvoiceDate",
                            "CompanyID",
                            "BranchID",
                            "BrandID"});
                table399.AddRow(new string[] {
                            "1FDKF37GXVEB34368",
                            "2026-01-15",
                            "1",
                            "10",
                            "1"});
#line 103
  await testRunner.GivenAsync("vehicles in dealer stock:", ((string)(null)), table399, "Given ");
#line hidden
                global::Reqnroll.Table table400 = new global::Reqnroll.Table(new string[] {
                            "ServiceItemID",
                            "Name",
                            "BrandID",
                            "ActiveForMonths",
                            "MaximumMileage",
                            "ProgramRole"});
                table400.AddRow(new string[] {
                            "SI-CONDITIONAL",
                            "Conditional schedule",
                            "1",
                            "6",
                            "80000",
                            ""});
                table400.AddRow(new string[] {
                            "SI-REWARD",
                            "Mileage reward",
                            "1",
                            "3",
                            "95000",
                            "Reward"});
#line 106
  await testRunner.AndAsync("service items:", ((string)(null)), table400, "And ");
#line hidden
                global::Reqnroll.Table table401 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Operator",
                            "Selection",
                            "Count",
                            "Values"});
                table401.AddRow(new string[] {
                            "serviceHistory.laborLines.packageCode",
                            "ContainsAll",
                            "Latest",
                            "1",
                            "absent"});
#line 110
  await testRunner.AndAsync("service item \"SI-CONDITIONAL\" has eligibility conditions:", ((string)(null)), table401, "And ");
#line hidden
                global::Reqnroll.Table table402 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Operator",
                            "Values"});
                table402.AddRow(new string[] {
                            "serviceItems.baseSchedule.maximumMileage",
                            "Equals",
                            "80000"});
#line 113
  await testRunner.AndAsync("service item \"SI-REWARD\" has eligibility conditions:", ((string)(null)), table402, "And ");
#line hidden
#line 116
  await testRunner.AndAsync("the free service start date is \"2026-01-15\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 117
  await testRunner.WhenAsync("evaluating service items for \"1FDKF37GXVEB34368\" with language \"en\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 118
  await testRunner.ThenAsync("service item \"SI-CONDITIONAL\" is not in the result", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 119
  await testRunner.AndAsync("service item \"SI-REWARD\" is in the result", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.TheoryAttribute(DisplayName="Malformed base schedule scalar values fail closed")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Service Item Program Roles and Base Schedule Cap")]
        [global::Xunit.TraitAttribute("Description", "Malformed base schedule scalar values fail closed")]
        [global::Xunit.InlineDataAttribute("[]", "8", new string[0])]
        [global::Xunit.InlineDataAttribute("[\"0\"]", "9", new string[0])]
        [global::Xunit.InlineDataAttribute("[\"-1\"]", "10", new string[0])]
        [global::Xunit.InlineDataAttribute("[\"40,000\"]", "11", new string[0])]
        [global::Xunit.InlineDataAttribute("[\" 40000\"]", "12", new string[0])]
        [global::Xunit.InlineDataAttribute("[\"40000\",\"50000\"]", "13", new string[0])]
        public async global::System.Threading.Tasks.Task MalformedBaseScheduleScalarValuesFailClosed(string valuesJson, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("ValuesJson", valuesJson);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Malformed base schedule scalar values fail closed", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 121
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table403 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "InvoiceDate",
                            "CompanyID",
                            "BranchID",
                            "BrandID"});
                table403.AddRow(new string[] {
                            "1FDKF37GXVEB34368",
                            "2026-01-15",
                            "1",
                            "10",
                            "1"});
#line 122
  await testRunner.GivenAsync("vehicles in dealer stock:", ((string)(null)), table403, "Given ");
#line hidden
                global::Reqnroll.Table table404 = new global::Reqnroll.Table(new string[] {
                            "ServiceItemID",
                            "Name",
                            "BrandID",
                            "ActiveForMonths",
                            "MaximumMileage",
                            "ProgramRole"});
                table404.AddRow(new string[] {
                            "SI-BASE",
                            "Base schedule end",
                            "1",
                            "6",
                            "40000",
                            ""});
                table404.AddRow(new string[] {
                            "SI-REWARD",
                            "Mileage reward",
                            "1",
                            "3",
                            "55000",
                            "Reward"});
#line 125
  await testRunner.AndAsync("service items:", ((string)(null)), table404, "And ");
#line hidden
                global::Reqnroll.Table table405 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Operator",
                            "ValuesJson"});
                table405.AddRow(new string[] {
                            "serviceItems.baseSchedule.maximumMileage",
                            "Equals",
                            string.Format("{0}", valuesJson)});
#line 129
  await testRunner.AndAsync("service item \"SI-REWARD\" has eligibility conditions:", ((string)(null)), table405, "And ");
#line hidden
#line 132
  await testRunner.AndAsync("the free service start date is \"2026-01-15\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 133
  await testRunner.WhenAsync("evaluating service items for \"1FDKF37GXVEB34368\" with language \"en\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 134
  await testRunner.ThenAsync("service item \"SI-REWARD\" is not in the result", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="A base schedule scalar condition with collection scope fails closed")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Service Item Program Roles and Base Schedule Cap")]
        [global::Xunit.TraitAttribute("Description", "A base schedule scalar condition with collection scope fails closed")]
        public async global::System.Threading.Tasks.Task ABaseScheduleScalarConditionWithCollectionScopeFailsClosed()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A base schedule scalar condition with collection scope fails closed", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 145
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table406 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "InvoiceDate",
                            "CompanyID",
                            "BranchID",
                            "BrandID"});
                table406.AddRow(new string[] {
                            "1FDKF37GXVEB34368",
                            "2026-01-15",
                            "1",
                            "10",
                            "1"});
#line 146
  await testRunner.GivenAsync("vehicles in dealer stock:", ((string)(null)), table406, "Given ");
#line hidden
                global::Reqnroll.Table table407 = new global::Reqnroll.Table(new string[] {
                            "ServiceItemID",
                            "Name",
                            "BrandID",
                            "ActiveForMonths",
                            "MaximumMileage",
                            "ProgramRole"});
                table407.AddRow(new string[] {
                            "SI-BASE",
                            "Base schedule end",
                            "1",
                            "6",
                            "40000",
                            ""});
                table407.AddRow(new string[] {
                            "SI-REWARD",
                            "Mileage reward",
                            "1",
                            "3",
                            "55000",
                            "Reward"});
#line 149
  await testRunner.AndAsync("service items:", ((string)(null)), table407, "And ");
#line hidden
                global::Reqnroll.Table table408 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Operator",
                            "Selection",
                            "Count",
                            "Values"});
                table408.AddRow(new string[] {
                            "serviceItems.baseSchedule.maximumMileage",
                            "Equals",
                            "Latest",
                            "1",
                            "40000"});
#line 153
  await testRunner.AndAsync("service item \"SI-REWARD\" has eligibility conditions:", ((string)(null)), table408, "And ");
#line hidden
#line 156
  await testRunner.AndAsync("the free service start date is \"2026-01-15\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 157
  await testRunner.WhenAsync("evaluating service items for \"1FDKF37GXVEB34368\" with language \"en\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 158
  await testRunner.ThenAsync("service item \"SI-REWARD\" is not in the result", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="A base schedule scalar condition with the wrong operator fails closed")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Service Item Program Roles and Base Schedule Cap")]
        [global::Xunit.TraitAttribute("Description", "A base schedule scalar condition with the wrong operator fails closed")]
        public async global::System.Threading.Tasks.Task ABaseScheduleScalarConditionWithTheWrongOperatorFailsClosed()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A base schedule scalar condition with the wrong operator fails closed", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 160
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table409 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "InvoiceDate",
                            "CompanyID",
                            "BranchID",
                            "BrandID"});
                table409.AddRow(new string[] {
                            "1FDKF37GXVEB34368",
                            "2026-01-15",
                            "1",
                            "10",
                            "1"});
#line 161
  await testRunner.GivenAsync("vehicles in dealer stock:", ((string)(null)), table409, "Given ");
#line hidden
                global::Reqnroll.Table table410 = new global::Reqnroll.Table(new string[] {
                            "ServiceItemID",
                            "Name",
                            "BrandID",
                            "ActiveForMonths",
                            "MaximumMileage",
                            "ProgramRole"});
                table410.AddRow(new string[] {
                            "SI-BASE",
                            "Base schedule end",
                            "1",
                            "6",
                            "40000",
                            ""});
                table410.AddRow(new string[] {
                            "SI-REWARD",
                            "Mileage reward",
                            "1",
                            "3",
                            "55000",
                            "Reward"});
#line 164
  await testRunner.AndAsync("service items:", ((string)(null)), table410, "And ");
#line hidden
                global::Reqnroll.Table table411 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Operator",
                            "Values"});
                table411.AddRow(new string[] {
                            "serviceItems.baseSchedule.maximumMileage",
                            "ContainsAll",
                            "40000"});
#line 168
  await testRunner.AndAsync("service item \"SI-REWARD\" has eligibility conditions:", ((string)(null)), table411, "And ");
#line hidden
#line 171
  await testRunner.AndAsync("the free service start date is \"2026-01-15\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 172
  await testRunner.WhenAsync("evaluating service items for \"1FDKF37GXVEB34368\" with language \"en\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 173
  await testRunner.ThenAsync("service item \"SI-REWARD\" is not in the result", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Rewards remain in mileage order and rolling expiry with their own duration")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Service Item Program Roles and Base Schedule Cap")]
        [global::Xunit.TraitAttribute("Description", "Rewards remain in mileage order and rolling expiry with their own duration")]
        public async global::System.Threading.Tasks.Task RewardsRemainInMileageOrderAndRollingExpiryWithTheirOwnDuration()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "16";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Rewards remain in mileage order and rolling expiry with their own duration", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 175
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 176
  await testRunner.GivenAsync("the current UTC time is \"2026-02-01 09:00:00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table412 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "InvoiceDate",
                            "CompanyID",
                            "BranchID",
                            "BrandID"});
                table412.AddRow(new string[] {
                            "1FDKF37GXVEB34368",
                            "2026-01-15",
                            "1",
                            "10",
                            "1"});
#line 177
  await testRunner.AndAsync("vehicles in dealer stock:", ((string)(null)), table412, "And ");
#line hidden
                global::Reqnroll.Table table413 = new global::Reqnroll.Table(new string[] {
                            "ServiceItemID",
                            "Name",
                            "BrandID",
                            "ActiveForMonths",
                            "MaximumMileage",
                            "ProgramRole"});
                table413.AddRow(new string[] {
                            "SI-BASE",
                            "Base schedule end",
                            "1",
                            "6",
                            "40000",
                            ""});
                table413.AddRow(new string[] {
                            "SI-REWARD",
                            "Mileage reward",
                            "1",
                            "3",
                            "55000",
                            "Reward"});
#line 180
  await testRunner.AndAsync("service items:", ((string)(null)), table413, "And ");
#line hidden
                global::Reqnroll.Table table414 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Operator",
                            "Values"});
                table414.AddRow(new string[] {
                            "serviceItems.baseSchedule.maximumMileage",
                            "Equals",
                            "40000"});
#line 184
  await testRunner.AndAsync("service item \"SI-REWARD\" has eligibility conditions:", ((string)(null)), table414, "And ");
#line hidden
#line 187
  await testRunner.AndAsync("a skipped items claim warning resolver is configured", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 188
  await testRunner.AndAsync("the free service start date is \"2026-01-15\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 189
  await testRunner.WhenAsync("evaluating service items for \"1FDKF37GXVEB34368\" with language \"en\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table415 = new global::Reqnroll.Table(new string[] {
                            "ServiceItemID"});
                table415.AddRow(new string[] {
                            "SI-BASE"});
                table415.AddRow(new string[] {
                            "SI-REWARD"});
#line 190
  await testRunner.ThenAsync("the service items in order are:", ((string)(null)), table415, "Then ");
#line hidden
#line 194
  await testRunner.AndAsync("service item \"SI-REWARD\" has type \"free\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 195
  await testRunner.AndAsync("service item \"SI-REWARD\" has activation \"2026-07-15\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 196
  await testRunner.AndAsync("service item \"SI-REWARD\" has expiration \"2026-10-15\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 197
  await testRunner.AndAsync("service item \"SI-REWARD\" has status \"pending\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 198
  await testRunner.AndAsync("service item \"SI-REWARD\" has a signature", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 199
  await testRunner.AndAsync("the warning with key \"skippedItems\" on service item \"SI-REWARD\" has body \"SI-BASE" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="A processed reward cancels lower-mileage pending free items")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Service Item Program Roles and Base Schedule Cap")]
        [global::Xunit.TraitAttribute("Description", "A processed reward cancels lower-mileage pending free items")]
        public async global::System.Threading.Tasks.Task AProcessedRewardCancelsLower_MileagePendingFreeItems()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "17";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A processed reward cancels lower-mileage pending free items", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 201
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 202
  await testRunner.GivenAsync("the current UTC time is \"2026-02-01 09:00:00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table416 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "InvoiceDate",
                            "CompanyID",
                            "BranchID",
                            "BrandID"});
                table416.AddRow(new string[] {
                            "1FDKF37GXVEB34368",
                            "2026-01-15",
                            "1",
                            "10",
                            "1"});
#line 203
  await testRunner.AndAsync("vehicles in dealer stock:", ((string)(null)), table416, "And ");
#line hidden
                global::Reqnroll.Table table417 = new global::Reqnroll.Table(new string[] {
                            "ServiceItemID",
                            "Name",
                            "BrandID",
                            "ActiveForMonths",
                            "MaximumMileage",
                            "ProgramRole"});
                table417.AddRow(new string[] {
                            "SI-BASE",
                            "Base schedule end",
                            "1",
                            "6",
                            "40000",
                            ""});
                table417.AddRow(new string[] {
                            "SI-REWARD",
                            "Mileage reward",
                            "1",
                            "3",
                            "55000",
                            "Reward"});
#line 206
  await testRunner.AndAsync("service items:", ((string)(null)), table417, "And ");
#line hidden
                global::Reqnroll.Table table418 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Operator",
                            "Values"});
                table418.AddRow(new string[] {
                            "serviceItems.baseSchedule.maximumMileage",
                            "Equals",
                            "40000"});
#line 210
  await testRunner.AndAsync("service item \"SI-REWARD\" has eligibility conditions:", ((string)(null)), table418, "And ");
#line hidden
                global::Reqnroll.Table table419 = new global::Reqnroll.Table(new string[] {
                            "ServiceItemID",
                            "ClaimDate",
                            "JobNumber",
                            "InvoiceNumber"});
                table419.AddRow(new string[] {
                            "SI-REWARD",
                            "2026-08-01",
                            "JOB-055",
                            "INV-055"});
#line 213
  await testRunner.AndAsync("item claims:", ((string)(null)), table419, "And ");
#line hidden
#line 216
  await testRunner.AndAsync("the free service start date is \"2026-01-15\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 217
  await testRunner.WhenAsync("evaluating service items for \"1FDKF37GXVEB34368\" with language \"en\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 218
  await testRunner.ThenAsync("service item \"SI-BASE\" has status \"cancelled\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 219
  await testRunner.AndAsync("service item \"SI-REWARD\" has status \"processed\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Free-item VIN exclusion removes a reward")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Service Item Program Roles and Base Schedule Cap")]
        [global::Xunit.TraitAttribute("Description", "Free-item VIN exclusion removes a reward")]
        public async global::System.Threading.Tasks.Task Free_ItemVINExclusionRemovesAReward()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "18";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Free-item VIN exclusion removes a reward", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 221
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table420 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "InvoiceDate",
                            "CompanyID",
                            "BranchID",
                            "BrandID"});
                table420.AddRow(new string[] {
                            "1FDKF37GXVEB34368",
                            "2026-01-15",
                            "1",
                            "10",
                            "1"});
#line 222
  await testRunner.GivenAsync("vehicles in dealer stock:", ((string)(null)), table420, "Given ");
#line hidden
                global::Reqnroll.Table table421 = new global::Reqnroll.Table(new string[] {
                            "ServiceItemID",
                            "Name",
                            "BrandID",
                            "ActiveForMonths",
                            "MaximumMileage",
                            "ProgramRole"});
                table421.AddRow(new string[] {
                            "SI-BASE",
                            "Base schedule end",
                            "1",
                            "6",
                            "40000",
                            ""});
                table421.AddRow(new string[] {
                            "SI-REWARD",
                            "Mileage reward",
                            "1",
                            "3",
                            "55000",
                            "Reward"});
#line 225
  await testRunner.AndAsync("service items:", ((string)(null)), table421, "And ");
#line hidden
                global::Reqnroll.Table table422 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Operator",
                            "Values"});
                table422.AddRow(new string[] {
                            "serviceItems.baseSchedule.maximumMileage",
                            "Equals",
                            "40000"});
#line 229
  await testRunner.AndAsync("service item \"SI-REWARD\" has eligibility conditions:", ((string)(null)), table422, "And ");
#line hidden
                global::Reqnroll.Table table423 = new global::Reqnroll.Table(new string[] {
                            "VIN"});
                table423.AddRow(new string[] {
                            "1FDKF37GXVEB34368"});
#line 232
  await testRunner.AndAsync("free service item excluded VINs:", ((string)(null)), table423, "And ");
#line hidden
#line 235
  await testRunner.AndAsync("the free service start date is \"2026-01-15\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 236
  await testRunner.WhenAsync("evaluating service items for \"1FDKF37GXVEB34368\" with language \"en\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 237
  await testRunner.ThenAsync("service item \"SI-REWARD\" is not in the result", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="A claimed reward remains visible when its eligibility conditions no longer match")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Service Item Program Roles and Base Schedule Cap")]
        [global::Xunit.TraitAttribute("Description", "A claimed reward remains visible when its eligibility conditions no longer match")]
        public async global::System.Threading.Tasks.Task AClaimedRewardRemainsVisibleWhenItsEligibilityConditionsNoLongerMatch()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "19";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A claimed reward remains visible when its eligibility conditions no longer match", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 239
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table424 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "InvoiceDate",
                            "CompanyID",
                            "BranchID",
                            "BrandID"});
                table424.AddRow(new string[] {
                            "1FDKF37GXVEB34368",
                            "2026-01-15",
                            "1",
                            "10",
                            "1"});
#line 240
  await testRunner.GivenAsync("vehicles in dealer stock:", ((string)(null)), table424, "Given ");
#line hidden
                global::Reqnroll.Table table425 = new global::Reqnroll.Table(new string[] {
                            "ServiceItemID",
                            "Name",
                            "BrandID",
                            "ActiveForMonths",
                            "MaximumMileage",
                            "ProgramRole"});
                table425.AddRow(new string[] {
                            "SI-BASE",
                            "Base schedule end",
                            "1",
                            "6",
                            "40000",
                            ""});
                table425.AddRow(new string[] {
                            "SI-REWARD",
                            "Mileage reward",
                            "1",
                            "3",
                            "55000",
                            "Reward"});
#line 243
  await testRunner.AndAsync("service items:", ((string)(null)), table425, "And ");
#line hidden
                global::Reqnroll.Table table426 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Operator",
                            "Values"});
                table426.AddRow(new string[] {
                            "serviceItems.baseSchedule.maximumMileage",
                            "Equals",
                            "60000"});
#line 247
  await testRunner.AndAsync("service item \"SI-REWARD\" has eligibility conditions:", ((string)(null)), table426, "And ");
#line hidden
                global::Reqnroll.Table table427 = new global::Reqnroll.Table(new string[] {
                            "ServiceItemID",
                            "ClaimDate",
                            "JobNumber",
                            "InvoiceNumber"});
                table427.AddRow(new string[] {
                            "SI-REWARD",
                            "2026-08-01",
                            "JOB-055",
                            "INV-055"});
#line 250
  await testRunner.AndAsync("item claims:", ((string)(null)), table427, "And ");
#line hidden
#line 253
  await testRunner.AndAsync("the free service start date is \"2026-01-15\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 254
  await testRunner.WhenAsync("evaluating service items for \"1FDKF37GXVEB34368\" with language \"en\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 255
  await testRunner.ThenAsync("service item \"SI-REWARD\" has status \"processed\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Paid invoice items never contribute to the catalog base schedule cap")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Service Item Program Roles and Base Schedule Cap")]
        [global::Xunit.TraitAttribute("Description", "Paid invoice items never contribute to the catalog base schedule cap")]
        public async global::System.Threading.Tasks.Task PaidInvoiceItemsNeverContributeToTheCatalogBaseScheduleCap()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "20";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Paid invoice items never contribute to the catalog base schedule cap", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 257
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table428 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "InvoiceDate",
                            "CompanyID",
                            "BranchID",
                            "BrandID"});
                table428.AddRow(new string[] {
                            "1FDKF37GXVEB34368",
                            "2026-01-15",
                            "1",
                            "10",
                            "1"});
#line 258
  await testRunner.GivenAsync("vehicles in dealer stock:", ((string)(null)), table428, "Given ");
#line hidden
                global::Reqnroll.Table table429 = new global::Reqnroll.Table(new string[] {
                            "ServiceItemID",
                            "Name",
                            "BrandID",
                            "ActiveForMonths",
                            "MaximumMileage",
                            "ProgramRole"});
                table429.AddRow(new string[] {
                            "SI-BASE",
                            "Base schedule end",
                            "1",
                            "6",
                            "40000",
                            ""});
                table429.AddRow(new string[] {
                            "SI-REWARD",
                            "Mileage reward",
                            "1",
                            "3",
                            "55000",
                            "Reward"});
#line 261
  await testRunner.AndAsync("service items:", ((string)(null)), table429, "And ");
#line hidden
                global::Reqnroll.Table table430 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Operator",
                            "Values"});
                table430.AddRow(new string[] {
                            "serviceItems.baseSchedule.maximumMileage",
                            "Equals",
                            "40000"});
#line 265
  await testRunner.AndAsync("service item \"SI-REWARD\" has eligibility conditions:", ((string)(null)), table430, "And ");
#line hidden
                global::Reqnroll.Table table431 = new global::Reqnroll.Table(new string[] {
                            "InvoiceDate",
                            "InvoiceNumber",
                            "ServiceItemID",
                            "ServiceItemName",
                            "MaximumMileage",
                            "ProgramRole"});
                table431.AddRow(new string[] {
                            "2026-03-15",
                            "1001",
                            "PSI-090",
                            "Paid service",
                            "90000",
                            "ScheduledService"});
#line 268
  await testRunner.AndAsync("paid service invoices:", ((string)(null)), table431, "And ");
#line hidden
#line 271
  await testRunner.AndAsync("the free service start date is \"2026-01-15\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 272
  await testRunner.WhenAsync("evaluating service items for \"1FDKF37GXVEB34368\" with language \"en\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 273
  await testRunner.ThenAsync("service item \"SI-REWARD\" is in the result", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 274
  await testRunner.AndAsync("service item \"PSI-090\" has type \"paid\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ServiceItemProgramRolesAndBaseScheduleCapFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
            {
                await ServiceItemProgramRolesAndBaseScheduleCapFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
