// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace LookupServices.BDD.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SSCPartAvailabilityFeature : object, Xunit.IClassFixture<SSCPartAvailabilityFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Xunit.ITestOutputHelper _testOutputHelper;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "SSC Part Availability", @"	Parts of open (not-yet-repaired) SSC (safety recall) records are flagged in-stock for Hub requesters who
	have a stock scope (their region / branch). Each part ends in one of three states: available (a positive
	AvailableQuantity in an in-scope stock location), not available (a scope was checked but no in-scope stock
	has a positive quantity), or not checked (the requester has no stock scope, or the recall is already
	repaired) — the last is left null so the UI can show it neutrally rather than as ""unavailable"". Part numbers
	are matched after mapping them to the deployment's stored key (by default: dashes removed, upper-cased).", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "VehicleSSCPartAvailability.feature"
#line hidden
        
        public SSCPartAvailabilityFeature(SSCPartAvailabilityFeature.FixtureData fixtureData, Xunit.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/VehicleSSCPartAvailability.feature.ndjson", 12);
        }
        
        async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Part with stock in the requester\'s scope is available")]
        [global::Xunit.TraitAttribute("FeatureTitle", "SSC Part Availability")]
        [global::Xunit.TraitAttribute("Description", "Part with stock in the requester\'s scope is available")]
        public async global::System.Threading.Tasks.Task PartWithStockInTheRequestersScopeIsAvailable()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Part with stock in the requester\'s scope is available", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Availability is scoped to the requester\'s stock locations", null, tagsOfRule);
#line 11
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "PartNumber1"});
                table1.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "90118WB001"});
#line 12
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table1, "Given ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Location",
                            "AvailableQuantity"});
                table2.AddRow(new string[] {
                            "region-a",
                            "4"});
#line 15
 await testRunner.AndAsync("stock for part \"90118WB001\":", ((string)(null)), table2, "And ");
#line hidden
#line 18
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
 await testRunner.AndAsync("SSC part availability is applied for stock scope \"region-a\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
 await testRunner.ThenAsync("SSC \"SSC-001\" part \"90118WB001\" is available", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Part with stock only outside the requester\'s scope is not available")]
        [global::Xunit.TraitAttribute("FeatureTitle", "SSC Part Availability")]
        [global::Xunit.TraitAttribute("Description", "Part with stock only outside the requester\'s scope is not available")]
        public async global::System.Threading.Tasks.Task PartWithStockOnlyOutsideTheRequestersScopeIsNotAvailable()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Part with stock only outside the requester\'s scope is not available", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Availability is scoped to the requester\'s stock locations", null, tagsOfRule);
#line 22
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "PartNumber1"});
                table3.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "90118WB001"});
#line 23
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table3, "Given ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Location",
                            "AvailableQuantity"});
                table4.AddRow(new string[] {
                            "region-b",
                            "9"});
#line 26
 await testRunner.AndAsync("stock for part \"90118WB001\":", ((string)(null)), table4, "And ");
#line hidden
#line 29
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 30
 await testRunner.AndAsync("SSC part availability is applied for stock scope \"region-a\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
 await testRunner.ThenAsync("SSC \"SSC-001\" part \"90118WB001\" is not available", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Part with zero quantity in scope is not available")]
        [global::Xunit.TraitAttribute("FeatureTitle", "SSC Part Availability")]
        [global::Xunit.TraitAttribute("Description", "Part with zero quantity in scope is not available")]
        public async global::System.Threading.Tasks.Task PartWithZeroQuantityInScopeIsNotAvailable()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Part with zero quantity in scope is not available", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Availability is scoped to the requester\'s stock locations", null, tagsOfRule);
#line 33
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "PartNumber1"});
                table5.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "90118WB001"});
#line 34
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table5, "Given ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "Location",
                            "AvailableQuantity"});
                table6.AddRow(new string[] {
                            "region-a",
                            "0"});
#line 37
 await testRunner.AndAsync("stock for part \"90118WB001\":", ((string)(null)), table6, "And ");
#line hidden
#line 40
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 41
 await testRunner.AndAsync("SSC part availability is applied for stock scope \"region-a\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
 await testRunner.ThenAsync("SSC \"SSC-001\" part \"90118WB001\" is not available", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Availability aggregates across multiple in-scope locations")]
        [global::Xunit.TraitAttribute("FeatureTitle", "SSC Part Availability")]
        [global::Xunit.TraitAttribute("Description", "Availability aggregates across multiple in-scope locations")]
        public async global::System.Threading.Tasks.Task AvailabilityAggregatesAcrossMultipleIn_ScopeLocations()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Availability aggregates across multiple in-scope locations", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Availability is scoped to the requester\'s stock locations", null, tagsOfRule);
#line 44
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "PartNumber1"});
                table7.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "90118WB001"});
#line 45
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table7, "Given ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "Location",
                            "AvailableQuantity"});
                table8.AddRow(new string[] {
                            "region-a",
                            "0"});
                table8.AddRow(new string[] {
                            "region-b",
                            "3"});
#line 48
 await testRunner.AndAsync("stock for part \"90118WB001\":", ((string)(null)), table8, "And ");
#line hidden
#line 52
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 53
 await testRunner.AndAsync("SSC part availability is applied for stock scope \"region-a,region-b\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 54
 await testRunner.ThenAsync("SSC \"SSC-001\" part \"90118WB001\" is available", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="No availability is checked when the feature is globally disabled")]
        [global::Xunit.TraitAttribute("FeatureTitle", "SSC Part Availability")]
        [global::Xunit.TraitAttribute("Description", "No availability is checked when the feature is globally disabled")]
        public async global::System.Threading.Tasks.Task NoAvailabilityIsCheckedWhenTheFeatureIsGloballyDisabled()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("No availability is checked when the feature is globally disabled", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The feature has a global on/off switch (EnableSSCPartAvailability)", null, tagsOfRule);
#line 58
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 59
 await testRunner.GivenAsync("SSC part availability is globally disabled", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 60
 await testRunner.AndAsync("the SSC stock scope resolver must not be called", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "PartNumber1"});
                table9.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "90118WB001"});
#line 61
 await testRunner.AndAsync("SSC affected vehicles:", ((string)(null)), table9, "And ");
#line hidden
#line 64
 await testRunner.WhenAsync("SSC part availability enrichment runs", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 65
 await testRunner.ThenAsync("SSC \"SSC-001\" part \"90118WB001\" availability is not checked", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Availability is not checked when the requester has no stock scope")]
        [global::Xunit.TraitAttribute("FeatureTitle", "SSC Part Availability")]
        [global::Xunit.TraitAttribute("Description", "Availability is not checked when the requester has no stock scope")]
        public async global::System.Threading.Tasks.Task AvailabilityIsNotCheckedWhenTheRequesterHasNoStockScope()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Availability is not checked when the requester has no stock scope", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A requester with no stock scope never sees availability", null, tagsOfRule);
#line 69
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "PartNumber1"});
                table10.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "90118WB001"});
#line 70
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table10, "Given ");
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "Location",
                            "AvailableQuantity"});
                table11.AddRow(new string[] {
                            "region-a",
                            "5"});
#line 73
 await testRunner.AndAsync("stock for part \"90118WB001\":", ((string)(null)), table11, "And ");
#line hidden
#line 76
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 77
 await testRunner.AndAsync("SSC part availability is applied for stock scope \"\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 78
 await testRunner.ThenAsync("SSC \"SSC-001\" part \"90118WB001\" availability is not checked", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="SSC part matches T-prefixed dash-stripped stock (deployment-specific storage key)" +
            "")]
        [global::Xunit.TraitAttribute("FeatureTitle", "SSC Part Availability")]
        [global::Xunit.TraitAttribute("Description", "SSC part matches T-prefixed dash-stripped stock (deployment-specific storage key)" +
            "")]
        public async global::System.Threading.Tasks.Task SSCPartMatchesT_PrefixedDash_StrippedStockDeployment_SpecificStorageKey()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("SSC part matches T-prefixed dash-stripped stock (deployment-specific storage key)" +
                    "", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Recall part numbers are mapped to the deployment\'s stored key", null, tagsOfRule);
#line 82
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 83
 await testRunner.GivenAsync("stock part numbers are stored T-prefixed and dash-stripped", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "PartNumber1"});
                table12.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "04007-07212"});
#line 84
 await testRunner.AndAsync("SSC affected vehicles:", ((string)(null)), table12, "And ");
#line hidden
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "Location",
                            "AvailableQuantity"});
                table13.AddRow(new string[] {
                            "region-a",
                            "3"});
#line 87
 await testRunner.AndAsync("stock for part \"T0400707212\":", ((string)(null)), table13, "And ");
#line hidden
#line 90
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 91
 await testRunner.AndAsync("SSC part availability is applied for stock scope \"region-a\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 92
 await testRunner.ThenAsync("SSC \"SSC-001\" part \"04007-07212\" is available", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="SSC part with no T-prefixed stock in scope is not available (deployment-specific " +
            "storage key)")]
        [global::Xunit.TraitAttribute("FeatureTitle", "SSC Part Availability")]
        [global::Xunit.TraitAttribute("Description", "SSC part with no T-prefixed stock in scope is not available (deployment-specific " +
            "storage key)")]
        public async global::System.Threading.Tasks.Task SSCPartWithNoT_PrefixedStockInScopeIsNotAvailableDeployment_SpecificStorageKey()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("SSC part with no T-prefixed stock in scope is not available (deployment-specific " +
                    "storage key)", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Recall part numbers are mapped to the deployment\'s stored key", null, tagsOfRule);
#line 94
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 95
 await testRunner.GivenAsync("stock part numbers are stored T-prefixed and dash-stripped", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "PartNumber1"});
                table14.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "04007-07212"});
#line 96
 await testRunner.AndAsync("SSC affected vehicles:", ((string)(null)), table14, "And ");
#line hidden
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "Location",
                            "AvailableQuantity"});
                table15.AddRow(new string[] {
                            "region-b",
                            "5"});
#line 99
 await testRunner.AndAsync("stock for part \"T0400707212\":", ((string)(null)), table15, "And ");
#line hidden
#line 102
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 103
 await testRunner.AndAsync("SSC part availability is applied for stock scope \"region-a\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 104
 await testRunner.ThenAsync("SSC \"SSC-001\" part \"04007-07212\" is not available", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Dashed recall part number matches dashless stock part number")]
        [global::Xunit.TraitAttribute("FeatureTitle", "SSC Part Availability")]
        [global::Xunit.TraitAttribute("Description", "Dashed recall part number matches dashless stock part number")]
        public async global::System.Threading.Tasks.Task DashedRecallPartNumberMatchesDashlessStockPartNumber()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Dashed recall part number matches dashless stock part number", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The default transform ignores dashes and case", null, tagsOfRule);
#line 108
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table16 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "PartNumber1"});
                table16.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "90118-WB001"});
#line 109
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table16, "Given ");
#line hidden
                global::Reqnroll.Table table17 = new global::Reqnroll.Table(new string[] {
                            "Location",
                            "AvailableQuantity"});
                table17.AddRow(new string[] {
                            "region-a",
                            "2"});
#line 112
 await testRunner.AndAsync("stock for part \"90118WB001\":", ((string)(null)), table17, "And ");
#line hidden
#line 115
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 116
 await testRunner.AndAsync("SSC part availability is applied for stock scope \"region-a\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 117
 await testRunner.ThenAsync("SSC \"SSC-001\" part \"90118-WB001\" is available", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="A repaired recall does not report part availability even when stock exists")]
        [global::Xunit.TraitAttribute("FeatureTitle", "SSC Part Availability")]
        [global::Xunit.TraitAttribute("Description", "A repaired recall does not report part availability even when stock exists")]
        public async global::System.Threading.Tasks.Task ARepairedRecallDoesNotReportPartAvailabilityEvenWhenStockExists()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A repaired recall does not report part availability even when stock exists", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Availability is only evaluated for recalls that are not yet repaired", null, tagsOfRule);
#line 121
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table18 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "PartNumber1",
                            "RepairDate"});
                table18.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "90118WB001",
                            "2020-05-01"});
#line 122
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table18, "Given ");
#line hidden
                global::Reqnroll.Table table19 = new global::Reqnroll.Table(new string[] {
                            "Location",
                            "AvailableQuantity"});
                table19.AddRow(new string[] {
                            "region-a",
                            "7"});
#line 125
 await testRunner.AndAsync("stock for part \"90118WB001\":", ((string)(null)), table19, "And ");
#line hidden
#line 128
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 129
 await testRunner.AndAsync("SSC part availability is applied for stock scope \"region-a\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 130
 await testRunner.ThenAsync("SSC \"SSC-001\" is marked as repaired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 131
 await testRunner.AndAsync("SSC \"SSC-001\" part \"90118WB001\" availability is not checked", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
            {
                await SSCPartAvailabilityFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
            {
                await SSCPartAvailabilityFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
