// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace LookupServices.BDD.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class VehicleSafetyServiceCampaignsSSCFeature : object, Xunit.IClassFixture<VehicleSafetyServiceCampaignsSSCFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Xunit.ITestOutputHelper _testOutputHelper;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Vehicle Safety Service Campaigns (SSC)", @"	Safety Service Campaigns (SSCs) are manufacturer-issued recalls or safety notices.
	Each SSC is checked for repair status by looking at three sources, in order; the first that holds
	decides both the verdict and the repair date, and is reported as the repair source:
	1. Direct RepairDate on the SSC record
	2. Matching warranty claim (by campaign code in distributor comment, or by labor code)
	3. Matching labor line (by labor code with invoice status X or C)
	A labor code matches directly or through a configured group of interchangeable codes: dealer
	systems sometimes book a campaign under a sibling operation code, and the deployment declares
	which codes are used interchangeably so those repairs are still recognised. Labor codes are
	compared trimmed and case-insensitively.
	When tracing is requested, every SSC carries a trace of the evidence behind its verdict.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "VehicleSSC.feature"
#line hidden
        
        public VehicleSafetyServiceCampaignsSSCFeature(VehicleSafetyServiceCampaignsSSCFeature.FixtureData fixtureData, Xunit.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/VehicleSSC.feature.ndjson", 31);
        }
        
        async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="SSC repaired via direct RepairDate")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "SSC repaired via direct RepairDate")]
        public async global::System.Threading.Tasks.Task SSCRepairedViaDirectRepairDate()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("SSC repaired via direct RepairDate", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Repair detected via direct RepairDate", null, tagsOfRule);
#line 16
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table741 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "RepairDate"});
                table741.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "2024-03-15"});
#line 17
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table741, "Given ");
#line hidden
#line 20
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 21
 await testRunner.ThenAsync("SSC \"SSC-001\" is marked as repaired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 22
 await testRunner.AndAsync("SSC \"SSC-001\" has repair date \"2024-03-15\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="SSC repaired via warranty claim matching campaign code in comment")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "SSC repaired via warranty claim matching campaign code in comment")]
        public async global::System.Threading.Tasks.Task SSCRepairedViaWarrantyClaimMatchingCampaignCodeInComment()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("SSC repaired via warranty claim matching campaign code in comment", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Repair detected via matching warranty claim", null, tagsOfRule);
#line 26
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table742 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1"});
                table742.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001"});
#line 27
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table742, "Given ");
#line hidden
                global::Reqnroll.Table table743 = new global::Reqnroll.Table(new string[] {
                            "ClaimStatus",
                            "RepairCompletionDate",
                            "DistributorComment"});
                table743.AddRow(new string[] {
                            "Accepted",
                            "2024-04-01",
                            "Repair for SSC-001 done"});
#line 30
 await testRunner.AndAsync("warranty claims:", ((string)(null)), table743, "And ");
#line hidden
#line 33
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 34
 await testRunner.ThenAsync("SSC \"SSC-001\" is marked as repaired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 35
 await testRunner.AndAsync("SSC \"SSC-001\" has repair date \"2024-04-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="SSC repaired via warranty claim matching labor code")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "SSC repaired via warranty claim matching labor code")]
        public async global::System.Threading.Tasks.Task SSCRepairedViaWarrantyClaimMatchingLaborCode()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("SSC repaired via warranty claim matching labor code", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Repair detected via matching warranty claim", null, tagsOfRule);
#line 37
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table744 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1"});
                table744.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001"});
#line 38
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table744, "Given ");
#line hidden
                global::Reqnroll.Table table745 = new global::Reqnroll.Table(new string[] {
                            "ClaimStatus",
                            "RepairCompletionDate",
                            "LaborCode"});
                table745.AddRow(new string[] {
                            "Certified",
                            "2024-05-10",
                            "LAB001"});
#line 41
 await testRunner.AndAsync("warranty claims:", ((string)(null)), table745, "And ");
#line hidden
#line 44
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 45
 await testRunner.ThenAsync("SSC \"SSC-001\" is marked as repaired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Warranty claim with non-matching status is ignored")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "Warranty claim with non-matching status is ignored")]
        public async global::System.Threading.Tasks.Task WarrantyClaimWithNon_MatchingStatusIsIgnored()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Warranty claim with non-matching status is ignored", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Repair detected via matching warranty claim", null, tagsOfRule);
#line 47
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table746 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1"});
                table746.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001"});
#line 48
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table746, "Given ");
#line hidden
                global::Reqnroll.Table table747 = new global::Reqnroll.Table(new string[] {
                            "ClaimStatus",
                            "RepairCompletionDate",
                            "DistributorComment"});
                table747.AddRow(new string[] {
                            "RejectedPermanently",
                            "2024-04-01",
                            "Repair for SSC-001"});
#line 51
 await testRunner.AndAsync("warranty claims:", ((string)(null)), table747, "And ");
#line hidden
#line 54
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 55
 await testRunner.ThenAsync("SSC \"SSC-001\" is marked as not repaired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="SSC repaired via labor line")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "SSC repaired via labor line")]
        public async global::System.Threading.Tasks.Task SSCRepairedViaLaborLine()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("SSC repaired via labor line", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Repair detected via matching labor line", null, tagsOfRule);
#line 59
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table748 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1"});
                table748.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001"});
#line 60
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table748, "Given ");
#line hidden
                global::Reqnroll.Table table749 = new global::Reqnroll.Table(new string[] {
                            "LaborCode",
                            "InvoiceDate",
                            "InvoiceStatus"});
                table749.AddRow(new string[] {
                            "LAB001",
                            "2024-06-01",
                            "X"});
#line 63
 await testRunner.AndAsync("labor lines:", ((string)(null)), table749, "And ");
#line hidden
#line 66
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 67
 await testRunner.ThenAsync("SSC \"SSC-001\" is marked as repaired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 68
 await testRunner.AndAsync("SSC \"SSC-001\" has repair date \"2024-06-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="SSC repaired via labor line with status C")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "SSC repaired via labor line with status C")]
        public async global::System.Threading.Tasks.Task SSCRepairedViaLaborLineWithStatusC()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("SSC repaired via labor line with status C", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Repair detected via matching labor line", null, tagsOfRule);
#line 70
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table750 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1"});
                table750.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001"});
#line 71
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table750, "Given ");
#line hidden
                global::Reqnroll.Table table751 = new global::Reqnroll.Table(new string[] {
                            "LaborCode",
                            "InvoiceDate",
                            "InvoiceStatus"});
                table751.AddRow(new string[] {
                            "LAB001",
                            "2024-07-01",
                            "C"});
#line 74
 await testRunner.AndAsync("labor lines:", ((string)(null)), table751, "And ");
#line hidden
#line 77
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 78
 await testRunner.ThenAsync("SSC \"SSC-001\" is marked as repaired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 79
 await testRunner.AndAsync("SSC \"SSC-001\" has repair date \"2024-07-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="SSC labor code with surrounding whitespace still matches the labor line")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "SSC labor code with surrounding whitespace still matches the labor line")]
        public async global::System.Threading.Tasks.Task SSCLaborCodeWithSurroundingWhitespaceStillMatchesTheLaborLine()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("SSC labor code with surrounding whitespace still matches the labor line", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Repair detected via matching labor line", null, tagsOfRule);
#line 81
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table752 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1"});
                table752.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "AURCM"});
#line 82
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table752, "Given ");
#line hidden
#line 85
 await testRunner.AndAsync("the SSC \"SSC-001\" labor code carries a trailing space", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table753 = new global::Reqnroll.Table(new string[] {
                            "LaborCode",
                            "InvoiceDate",
                            "InvoiceStatus"});
                table753.AddRow(new string[] {
                            "AURCM",
                            "2024-06-01",
                            "X"});
#line 86
 await testRunner.AndAsync("labor lines:", ((string)(null)), table753, "And ");
#line hidden
#line 89
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 90
 await testRunner.ThenAsync("SSC \"SSC-001\" is marked as repaired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 91
 await testRunner.AndAsync("SSC \"SSC-001\" has repair date \"2024-06-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Labor line with non-matching status is ignored")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "Labor line with non-matching status is ignored")]
        public async global::System.Threading.Tasks.Task LaborLineWithNon_MatchingStatusIsIgnored()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Labor line with non-matching status is ignored", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Repair detected via matching labor line", null, tagsOfRule);
#line 93
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table754 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1"});
                table754.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001"});
#line 94
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table754, "Given ");
#line hidden
                global::Reqnroll.Table table755 = new global::Reqnroll.Table(new string[] {
                            "LaborCode",
                            "InvoiceDate",
                            "InvoiceStatus"});
                table755.AddRow(new string[] {
                            "LAB001",
                            "2024-06-01",
                            "O"});
#line 97
 await testRunner.AndAsync("labor lines:", ((string)(null)), table755, "And ");
#line hidden
#line 100
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 101
 await testRunner.ThenAsync("SSC \"SSC-001\" is marked as not repaired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="SSC not repaired when no evidence found")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "SSC not repaired when no evidence found")]
        public async global::System.Threading.Tasks.Task SSCNotRepairedWhenNoEvidenceFound()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("SSC not repaired when no evidence found", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("No repair evidence", null, tagsOfRule);
#line 105
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table756 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1"});
                table756.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001"});
#line 106
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table756, "Given ");
#line hidden
#line 109
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 110
 await testRunner.ThenAsync("SSC \"SSC-001\" is marked as not repaired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="No SSC records returns null")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "No SSC records returns null")]
        public async global::System.Threading.Tasks.Task NoSSCRecordsReturnsNull()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("No SSC records returns null", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("No repair evidence", null, tagsOfRule);
#line 112
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 113
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 114
 await testRunner.ThenAsync("there are no SSC records", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Multiple SSCs with mixed repair status")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "Multiple SSCs with mixed repair status")]
        public async global::System.Threading.Tasks.Task MultipleSSCsWithMixedRepairStatus()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Multiple SSCs with mixed repair status", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Result composition", null, tagsOfRule);
#line 118
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table757 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1",
                            "RepairDate"});
                table757.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001",
                            "2024-03-15"});
                table757.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-002",
                            "Seatbelt recall",
                            "LAB002",
                            ""});
#line 119
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table757, "Given ");
#line hidden
#line 123
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 124
 await testRunner.ThenAsync("SSC \"SSC-001\" is marked as repaired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 125
 await testRunner.AndAsync("SSC \"SSC-002\" is marked as not repaired", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="SSC parts and labor codes appear in result")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "SSC parts and labor codes appear in result")]
        public async global::System.Threading.Tasks.Task SSCPartsAndLaborCodesAppearInResult()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("SSC parts and labor codes appear in result", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Result composition", null, tagsOfRule);
#line 127
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table758 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1",
                            "LaborCode2",
                            "PartNumber1",
                            "PartNumber2"});
                table758.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001",
                            "LAB002",
                            "PRT001",
                            "PRT002"});
#line 128
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table758, "Given ");
#line hidden
#line 131
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 132
 await testRunner.ThenAsync("SSC \"SSC-001\" has 2 labor codes", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 133
 await testRunner.AndAsync("SSC \"SSC-001\" has 2 part numbers", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="SSC exposes more than three parts and labor codes")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "SSC exposes more than three parts and labor codes")]
        public async global::System.Threading.Tasks.Task SSCExposesMoreThanThreePartsAndLaborCodes()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("SSC exposes more than three parts and labor codes", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Result composition", null, tagsOfRule);
#line 135
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table759 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1",
                            "LaborCode2",
                            "LaborCode3",
                            "LaborCode4",
                            "LaborCode5",
                            "LaborCode6",
                            "PartNumber1",
                            "PartNumber2",
                            "PartNumber3",
                            "PartNumber4",
                            "PartNumber5",
                            "PartNumber6"});
                table759.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001",
                            "LAB002",
                            "LAB003",
                            "LAB004",
                            "LAB005",
                            "LAB006",
                            "PRT001",
                            "PRT002",
                            "PRT003",
                            "PRT004",
                            "PRT005",
                            "PRT006"});
#line 136
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table759, "Given ");
#line hidden
#line 139
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 140
 await testRunner.ThenAsync("SSC \"SSC-001\" has 6 labor codes", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 141
 await testRunner.AndAsync("SSC \"SSC-001\" has 6 part numbers", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="SSC stored in legacy numbered fields is still evaluated")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "SSC stored in legacy numbered fields is still evaluated")]
        public async global::System.Threading.Tasks.Task SSCStoredInLegacyNumberedFieldsIsStillEvaluated()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("SSC stored in legacy numbered fields is still evaluated", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Backward compatibility with legacy numbered fields", null, tagsOfRule);
#line 145
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table760 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1",
                            "LaborCode2",
                            "PartNumber1"});
                table760.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001",
                            "LAB002",
                            "PRT001"});
#line 146
 await testRunner.GivenAsync("SSC affected vehicles in legacy numbered format:", ((string)(null)), table760, "Given ");
#line hidden
#line 149
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 150
 await testRunner.ThenAsync("SSC \"SSC-001\" has 2 labor codes", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 151
 await testRunner.AndAsync("SSC \"SSC-001\" has 1 part numbers", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Legacy labor code still drives repair detection")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "Legacy labor code still drives repair detection")]
        public async global::System.Threading.Tasks.Task LegacyLaborCodeStillDrivesRepairDetection()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Legacy labor code still drives repair detection", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Backward compatibility with legacy numbered fields", null, tagsOfRule);
#line 153
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table761 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1"});
                table761.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001"});
#line 154
 await testRunner.GivenAsync("SSC affected vehicles in legacy numbered format:", ((string)(null)), table761, "Given ");
#line hidden
                global::Reqnroll.Table table762 = new global::Reqnroll.Table(new string[] {
                            "LaborCode",
                            "InvoiceDate",
                            "InvoiceStatus"});
                table762.AddRow(new string[] {
                            "LAB001",
                            "2024-06-01",
                            "X"});
#line 157
 await testRunner.AndAsync("labor lines:", ((string)(null)), table762, "And ");
#line hidden
#line 160
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 161
 await testRunner.ThenAsync("SSC \"SSC-001\" is marked as repaired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 162
 await testRunner.AndAsync("SSC \"SSC-001\" has repair date \"2024-06-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="SSC repaired via warranty claim carrying an interchangeable labor code")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "SSC repaired via warranty claim carrying an interchangeable labor code")]
        public async global::System.Threading.Tasks.Task SSCRepairedViaWarrantyClaimCarryingAnInterchangeableLaborCode()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("SSC repaired via warranty claim carrying an interchangeable labor code", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Interchangeable labor codes", null, tagsOfRule);
#line 166
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table763 = new global::Reqnroll.Table(new string[] {
                            "Codes"});
                table763.AddRow(new string[] {
                            "LAB001, LAB001A, LAB0010"});
#line 167
 await testRunner.GivenAsync("interchangeable SSC labor codes:", ((string)(null)), table763, "Given ");
#line hidden
                global::Reqnroll.Table table764 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1"});
                table764.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001"});
#line 170
 await testRunner.AndAsync("SSC affected vehicles:", ((string)(null)), table764, "And ");
#line hidden
                global::Reqnroll.Table table765 = new global::Reqnroll.Table(new string[] {
                            "ClaimStatus",
                            "RepairCompletionDate",
                            "LaborCode"});
                table765.AddRow(new string[] {
                            "Accepted",
                            "2024-05-10",
                            "LAB001A"});
#line 173
 await testRunner.AndAsync("warranty claims:", ((string)(null)), table765, "And ");
#line hidden
#line 176
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 177
 await testRunner.ThenAsync("SSC \"SSC-001\" is marked as repaired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 178
 await testRunner.AndAsync("SSC \"SSC-001\" has repair date \"2024-05-10\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 179
 await testRunner.AndAsync("SSC \"SSC-001\" repair source is \"WarrantyClaim\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="SSC repaired via labor line carrying an interchangeable labor code")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "SSC repaired via labor line carrying an interchangeable labor code")]
        public async global::System.Threading.Tasks.Task SSCRepairedViaLaborLineCarryingAnInterchangeableLaborCode()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "16";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("SSC repaired via labor line carrying an interchangeable labor code", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Interchangeable labor codes", null, tagsOfRule);
#line 181
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table766 = new global::Reqnroll.Table(new string[] {
                            "Codes"});
                table766.AddRow(new string[] {
                            "LAB001, LAB001A"});
#line 182
 await testRunner.GivenAsync("interchangeable SSC labor codes:", ((string)(null)), table766, "Given ");
#line hidden
                global::Reqnroll.Table table767 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1"});
                table767.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001"});
#line 185
 await testRunner.AndAsync("SSC affected vehicles:", ((string)(null)), table767, "And ");
#line hidden
                global::Reqnroll.Table table768 = new global::Reqnroll.Table(new string[] {
                            "LaborCode",
                            "InvoiceDate",
                            "InvoiceStatus"});
                table768.AddRow(new string[] {
                            "LAB001A",
                            "2024-06-01",
                            "X"});
#line 188
 await testRunner.AndAsync("labor lines:", ((string)(null)), table768, "And ");
#line hidden
#line 191
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 192
 await testRunner.ThenAsync("SSC \"SSC-001\" is marked as repaired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 193
 await testRunner.AndAsync("SSC \"SSC-001\" has repair date \"2024-06-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 194
 await testRunner.AndAsync("SSC \"SSC-001\" repair source is \"ServiceHistory\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Interchangeability is symmetric so the campaign may list either code")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "Interchangeability is symmetric so the campaign may list either code")]
        public async global::System.Threading.Tasks.Task InterchangeabilityIsSymmetricSoTheCampaignMayListEitherCode()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "17";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Interchangeability is symmetric so the campaign may list either code", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Interchangeable labor codes", null, tagsOfRule);
#line 196
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table769 = new global::Reqnroll.Table(new string[] {
                            "Codes"});
                table769.AddRow(new string[] {
                            "LAB001, LAB001A"});
#line 197
 await testRunner.GivenAsync("interchangeable SSC labor codes:", ((string)(null)), table769, "Given ");
#line hidden
                global::Reqnroll.Table table770 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1"});
                table770.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001A"});
#line 200
 await testRunner.AndAsync("SSC affected vehicles:", ((string)(null)), table770, "And ");
#line hidden
                global::Reqnroll.Table table771 = new global::Reqnroll.Table(new string[] {
                            "LaborCode",
                            "InvoiceDate",
                            "InvoiceStatus"});
                table771.AddRow(new string[] {
                            "LAB001",
                            "2024-06-01",
                            "C"});
#line 203
 await testRunner.AndAsync("labor lines:", ((string)(null)), table771, "And ");
#line hidden
#line 206
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 207
 await testRunner.ThenAsync("SSC \"SSC-001\" is marked as repaired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Interchangeability is transitive across groups that share a code")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "Interchangeability is transitive across groups that share a code")]
        public async global::System.Threading.Tasks.Task InterchangeabilityIsTransitiveAcrossGroupsThatShareACode()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "18";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Interchangeability is transitive across groups that share a code", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Interchangeable labor codes", null, tagsOfRule);
#line 209
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table772 = new global::Reqnroll.Table(new string[] {
                            "Codes"});
                table772.AddRow(new string[] {
                            "LAB001, LAB001A"});
                table772.AddRow(new string[] {
                            "LAB001A, LAB001B"});
#line 210
 await testRunner.GivenAsync("interchangeable SSC labor codes:", ((string)(null)), table772, "Given ");
#line hidden
                global::Reqnroll.Table table773 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1"});
                table773.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001"});
#line 214
 await testRunner.AndAsync("SSC affected vehicles:", ((string)(null)), table773, "And ");
#line hidden
                global::Reqnroll.Table table774 = new global::Reqnroll.Table(new string[] {
                            "LaborCode",
                            "InvoiceDate",
                            "InvoiceStatus"});
                table774.AddRow(new string[] {
                            "LAB001B",
                            "2024-06-01",
                            "X"});
#line 217
 await testRunner.AndAsync("labor lines:", ((string)(null)), table774, "And ");
#line hidden
#line 220
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 221
 await testRunner.ThenAsync("SSC \"SSC-001\" is marked as repaired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="A code outside the interchangeable group is not repair evidence")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "A code outside the interchangeable group is not repair evidence")]
        public async global::System.Threading.Tasks.Task ACodeOutsideTheInterchangeableGroupIsNotRepairEvidence()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "19";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A code outside the interchangeable group is not repair evidence", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Interchangeable labor codes", null, tagsOfRule);
#line 223
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table775 = new global::Reqnroll.Table(new string[] {
                            "Codes"});
                table775.AddRow(new string[] {
                            "LAB001, LAB001A"});
#line 224
 await testRunner.GivenAsync("interchangeable SSC labor codes:", ((string)(null)), table775, "Given ");
#line hidden
                global::Reqnroll.Table table776 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1"});
                table776.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001"});
#line 227
 await testRunner.AndAsync("SSC affected vehicles:", ((string)(null)), table776, "And ");
#line hidden
                global::Reqnroll.Table table777 = new global::Reqnroll.Table(new string[] {
                            "LaborCode",
                            "InvoiceDate",
                            "InvoiceStatus"});
                table777.AddRow(new string[] {
                            "LAB001B",
                            "2024-06-01",
                            "X"});
#line 230
 await testRunner.AndAsync("labor lines:", ((string)(null)), table777, "And ");
#line hidden
                global::Reqnroll.Table table778 = new global::Reqnroll.Table(new string[] {
                            "ClaimStatus",
                            "RepairCompletionDate",
                            "LaborCode"});
                table778.AddRow(new string[] {
                            "Accepted",
                            "2024-05-10",
                            "LAB001B"});
#line 233
 await testRunner.AndAsync("warranty claims:", ((string)(null)), table778, "And ");
#line hidden
#line 236
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 237
 await testRunner.ThenAsync("SSC \"SSC-001\" is marked as not repaired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Interchangeable codes do not change the campaign\'s own labor code list")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "Interchangeable codes do not change the campaign\'s own labor code list")]
        public async global::System.Threading.Tasks.Task InterchangeableCodesDoNotChangeTheCampaignsOwnLaborCodeList()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "20";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Interchangeable codes do not change the campaign\'s own labor code list", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Interchangeable labor codes", null, tagsOfRule);
#line 239
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table779 = new global::Reqnroll.Table(new string[] {
                            "Codes"});
                table779.AddRow(new string[] {
                            "LAB001, LAB001A"});
#line 240
 await testRunner.GivenAsync("interchangeable SSC labor codes:", ((string)(null)), table779, "Given ");
#line hidden
                global::Reqnroll.Table table780 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1"});
                table780.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001"});
#line 243
 await testRunner.AndAsync("SSC affected vehicles:", ((string)(null)), table780, "And ");
#line hidden
#line 246
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 247
 await testRunner.ThenAsync("SSC \"SSC-001\" has 1 labor codes", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Labor code matching ignores case")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "Labor code matching ignores case")]
        public async global::System.Threading.Tasks.Task LaborCodeMatchingIgnoresCase()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "21";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Labor code matching ignores case", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Interchangeable labor codes", null, tagsOfRule);
#line 249
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table781 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1"});
                table781.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001"});
#line 250
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table781, "Given ");
#line hidden
                global::Reqnroll.Table table782 = new global::Reqnroll.Table(new string[] {
                            "LaborCode",
                            "InvoiceDate",
                            "InvoiceStatus"});
                table782.AddRow(new string[] {
                            "lab001",
                            "2024-06-01",
                            "X"});
#line 253
 await testRunner.AndAsync("labor lines:", ((string)(null)), table782, "And ");
#line hidden
#line 256
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 257
 await testRunner.ThenAsync("SSC \"SSC-001\" is marked as repaired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="The SSC record\'s own repair date outranks a matching warranty claim")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "The SSC record\'s own repair date outranks a matching warranty claim")]
        public async global::System.Threading.Tasks.Task TheSSCRecordsOwnRepairDateOutranksAMatchingWarrantyClaim()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "22";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The SSC record\'s own repair date outranks a matching warranty claim", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Repair source and precedence", null, tagsOfRule);
#line 261
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table783 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1",
                            "RepairDate"});
                table783.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001",
                            "2024-03-15"});
#line 262
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table783, "Given ");
#line hidden
                global::Reqnroll.Table table784 = new global::Reqnroll.Table(new string[] {
                            "ClaimStatus",
                            "RepairCompletionDate",
                            "LaborCode"});
                table784.AddRow(new string[] {
                            "Accepted",
                            "2024-04-01",
                            "LAB001"});
#line 265
 await testRunner.AndAsync("warranty claims:", ((string)(null)), table784, "And ");
#line hidden
#line 268
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 269
 await testRunner.ThenAsync("SSC \"SSC-001\" is marked as repaired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 270
 await testRunner.AndAsync("SSC \"SSC-001\" has repair date \"2024-03-15\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 271
 await testRunner.AndAsync("SSC \"SSC-001\" repair source is \"SSCRecord\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="A matching warranty claim outranks a matching labor line")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "A matching warranty claim outranks a matching labor line")]
        public async global::System.Threading.Tasks.Task AMatchingWarrantyClaimOutranksAMatchingLaborLine()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "23";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A matching warranty claim outranks a matching labor line", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Repair source and precedence", null, tagsOfRule);
#line 273
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table785 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1"});
                table785.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001"});
#line 274
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table785, "Given ");
#line hidden
                global::Reqnroll.Table table786 = new global::Reqnroll.Table(new string[] {
                            "ClaimStatus",
                            "RepairCompletionDate",
                            "LaborCode"});
                table786.AddRow(new string[] {
                            "Accepted",
                            "2024-04-01",
                            "LAB001"});
#line 277
 await testRunner.AndAsync("warranty claims:", ((string)(null)), table786, "And ");
#line hidden
                global::Reqnroll.Table table787 = new global::Reqnroll.Table(new string[] {
                            "LaborCode",
                            "InvoiceDate",
                            "InvoiceStatus"});
                table787.AddRow(new string[] {
                            "LAB001",
                            "2024-06-01",
                            "X"});
#line 280
 await testRunner.AndAsync("labor lines:", ((string)(null)), table787, "And ");
#line hidden
#line 283
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 284
 await testRunner.ThenAsync("SSC \"SSC-001\" has repair date \"2024-04-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 285
 await testRunner.AndAsync("SSC \"SSC-001\" repair source is \"WarrantyClaim\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="An open SSC reports no repair source")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "An open SSC reports no repair source")]
        public async global::System.Threading.Tasks.Task AnOpenSSCReportsNoRepairSource()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "24";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An open SSC reports no repair source", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Repair source and precedence", null, tagsOfRule);
#line 287
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table788 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1"});
                table788.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001"});
#line 288
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table788, "Given ");
#line hidden
#line 291
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 292
 await testRunner.ThenAsync("SSC \"SSC-001\" is marked as not repaired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 293
 await testRunner.AndAsync("SSC \"SSC-001\" repair source is \"None\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="The trace is omitted unless requested")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "The trace is omitted unless requested")]
        public async global::System.Threading.Tasks.Task TheTraceIsOmittedUnlessRequested()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "25";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The trace is omitted unless requested", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Evaluation trace", null, tagsOfRule);
#line 297
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table789 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1"});
                table789.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001"});
#line 298
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table789, "Given ");
#line hidden
#line 301
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 302
 await testRunner.ThenAsync("SSC \"SSC-001\" has no trace", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="The trace explains a repair found through an interchangeable code on a warranty c" +
            "laim")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "The trace explains a repair found through an interchangeable code on a warranty c" +
            "laim")]
        public async global::System.Threading.Tasks.Task TheTraceExplainsARepairFoundThroughAnInterchangeableCodeOnAWarrantyClaim()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "26";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The trace explains a repair found through an interchangeable code on a warranty c" +
                    "laim", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Evaluation trace", null, tagsOfRule);
#line 304
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 305
 await testRunner.GivenAsync("SSC evaluation tracing is requested", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table790 = new global::Reqnroll.Table(new string[] {
                            "Codes"});
                table790.AddRow(new string[] {
                            "LAB001, LAB001A"});
#line 306
 await testRunner.AndAsync("interchangeable SSC labor codes:", ((string)(null)), table790, "And ");
#line hidden
                global::Reqnroll.Table table791 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1"});
                table791.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001"});
#line 309
 await testRunner.AndAsync("SSC affected vehicles:", ((string)(null)), table791, "And ");
#line hidden
                global::Reqnroll.Table table792 = new global::Reqnroll.Table(new string[] {
                            "ClaimStatus",
                            "RepairCompletionDate",
                            "LaborCode"});
                table792.AddRow(new string[] {
                            "Accepted",
                            "2024-05-10",
                            "LAB001A"});
                table792.AddRow(new string[] {
                            "RejectedPermanently",
                            "2024-04-01",
                            "LAB001"});
#line 312
 await testRunner.AndAsync("warranty claims:", ((string)(null)), table792, "And ");
#line hidden
#line 316
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 317
 await testRunner.ThenAsync("SSC \"SSC-001\" trace lists interchangeable code \"LAB001A\" standing for \"LAB001\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 318
 await testRunner.AndAsync("SSC \"SSC-001\" trace warranty claim completed on \"2024-05-10\" is selected with lab" +
                        "or code \"LAB001A\" standing for \"LAB001\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 319
 await testRunner.AndAsync("SSC \"SSC-001\" trace warranty claim completed on \"2024-04-01\" matches but does not" +
                        " qualify by status", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 320
 await testRunner.AndAsync("SSC \"SSC-001\" trace repair source is \"WarrantyClaim\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="The trace explains a repair found in service history")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "The trace explains a repair found in service history")]
        public async global::System.Threading.Tasks.Task TheTraceExplainsARepairFoundInServiceHistory()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "27";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The trace explains a repair found in service history", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Evaluation trace", null, tagsOfRule);
#line 322
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 323
 await testRunner.GivenAsync("SSC evaluation tracing is requested", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table793 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1"});
                table793.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001"});
#line 324
 await testRunner.AndAsync("SSC affected vehicles:", ((string)(null)), table793, "And ");
#line hidden
                global::Reqnroll.Table table794 = new global::Reqnroll.Table(new string[] {
                            "LaborCode",
                            "InvoiceDate",
                            "InvoiceStatus",
                            "InvoiceNumber"});
                table794.AddRow(new string[] {
                            "LAB001",
                            "2024-06-01",
                            "X",
                            "INV-1"});
                table794.AddRow(new string[] {
                            "LAB999",
                            "2024-07-01",
                            "X",
                            "INV-2"});
#line 327
 await testRunner.AndAsync("labor lines:", ((string)(null)), table794, "And ");
#line hidden
#line 331
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 332
 await testRunner.ThenAsync("SSC \"SSC-001\" trace examined 2 service history labor lines and lists 1 matching", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 333
 await testRunner.AndAsync("SSC \"SSC-001\" trace labor line invoiced on \"2024-06-01\" is selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 334
 await testRunner.AndAsync("SSC \"SSC-001\" trace repair source is \"ServiceHistory\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="The trace explains why an SSC is still open")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "The trace explains why an SSC is still open")]
        public async global::System.Threading.Tasks.Task TheTraceExplainsWhyAnSSCIsStillOpen()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "28";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The trace explains why an SSC is still open", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Evaluation trace", null, tagsOfRule);
#line 336
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 337
 await testRunner.GivenAsync("SSC evaluation tracing is requested", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table795 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1"});
                table795.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001"});
#line 338
 await testRunner.AndAsync("SSC affected vehicles:", ((string)(null)), table795, "And ");
#line hidden
                global::Reqnroll.Table table796 = new global::Reqnroll.Table(new string[] {
                            "ClaimStatus",
                            "RepairCompletionDate",
                            "LaborCode"});
                table796.AddRow(new string[] {
                            "RejectedPermanently",
                            "2024-04-01",
                            "LAB001"});
                table796.AddRow(new string[] {
                            "Accepted",
                            "2024-02-01",
                            "LAB999"});
#line 341
 await testRunner.AndAsync("warranty claims:", ((string)(null)), table796, "And ");
#line hidden
                global::Reqnroll.Table table797 = new global::Reqnroll.Table(new string[] {
                            "LaborCode",
                            "InvoiceDate",
                            "InvoiceStatus"});
                table797.AddRow(new string[] {
                            "LAB001",
                            "2024-06-01",
                            "O"});
                table797.AddRow(new string[] {
                            "LAB999",
                            "2024-07-01",
                            "X"});
#line 345
 await testRunner.AndAsync("labor lines:", ((string)(null)), table797, "And ");
#line hidden
#line 349
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 350
 await testRunner.ThenAsync("SSC \"SSC-001\" is marked as not repaired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 351
 await testRunner.AndAsync("SSC \"SSC-001\" trace has 2 warranty claims and none selected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 352
 await testRunner.AndAsync("SSC \"SSC-001\" trace warranty claim completed on \"2024-04-01\" matches but does not" +
                        " qualify by status", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 353
 await testRunner.AndAsync("SSC \"SSC-001\" trace warranty claim completed on \"2024-02-01\" qualifies by status " +
                        "but does not match", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 354
 await testRunner.AndAsync("SSC \"SSC-001\" trace examined 2 service history labor lines and lists 1 matching", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 355
 await testRunner.AndAsync("SSC \"SSC-001\" trace labor line invoiced on \"2024-06-01\" does not qualify by statu" +
                        "s", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 356
 await testRunner.AndAsync("SSC \"SSC-001\" trace repair source is \"None\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
            {
                await VehicleSafetyServiceCampaignsSSCFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
            {
                await VehicleSafetyServiceCampaignsSSCFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
