// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace LookupServices.BDD.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class VehicleSafetyServiceCampaignsSSCFeature : object, Xunit.IClassFixture<VehicleSafetyServiceCampaignsSSCFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Xunit.ITestOutputHelper _testOutputHelper;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Vehicle Safety Service Campaigns (SSC)", @"	Safety Service Campaigns (SSCs) are manufacturer-issued recalls or safety notices.
	Each SSC is checked for repair status by looking at three sources:
	1. Direct RepairDate on the SSC record
	2. Matching warranty claim (by campaign code in distributor comment, or by labor code)
	3. Matching labor line (by labor code with invoice status X or C)", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "VehicleSSC.feature"
#line hidden
        
        public VehicleSafetyServiceCampaignsSSCFeature(VehicleSafetyServiceCampaignsSSCFeature.FixtureData fixtureData, Xunit.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/VehicleSSC.feature.ndjson", 13);
        }
        
        async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="SSC repaired via direct RepairDate")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "SSC repaired via direct RepairDate")]
        public async global::System.Threading.Tasks.Task SSCRepairedViaDirectRepairDate()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("SSC repaired via direct RepairDate", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Repair detected via direct RepairDate", null, tagsOfRule);
#line 10
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table237 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "RepairDate"});
                table237.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "2024-03-15"});
#line 11
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table237, "Given ");
#line hidden
#line 14
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 15
 await testRunner.ThenAsync("SSC \"SSC-001\" is marked as repaired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 16
 await testRunner.AndAsync("SSC \"SSC-001\" has repair date \"2024-03-15\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="SSC repaired via warranty claim matching campaign code in comment")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "SSC repaired via warranty claim matching campaign code in comment")]
        public async global::System.Threading.Tasks.Task SSCRepairedViaWarrantyClaimMatchingCampaignCodeInComment()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("SSC repaired via warranty claim matching campaign code in comment", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Repair detected via matching warranty claim", null, tagsOfRule);
#line 20
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table238 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1"});
                table238.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001"});
#line 21
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table238, "Given ");
#line hidden
                global::Reqnroll.Table table239 = new global::Reqnroll.Table(new string[] {
                            "ClaimStatus",
                            "RepairCompletionDate",
                            "DistributorComment"});
                table239.AddRow(new string[] {
                            "Accepted",
                            "2024-04-01",
                            "Repair for SSC-001 done"});
#line 24
 await testRunner.AndAsync("warranty claims:", ((string)(null)), table239, "And ");
#line hidden
#line 27
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 28
 await testRunner.ThenAsync("SSC \"SSC-001\" is marked as repaired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 29
 await testRunner.AndAsync("SSC \"SSC-001\" has repair date \"2024-04-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="SSC repaired via warranty claim matching labor code")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "SSC repaired via warranty claim matching labor code")]
        public async global::System.Threading.Tasks.Task SSCRepairedViaWarrantyClaimMatchingLaborCode()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("SSC repaired via warranty claim matching labor code", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Repair detected via matching warranty claim", null, tagsOfRule);
#line 31
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table240 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1"});
                table240.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001"});
#line 32
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table240, "Given ");
#line hidden
                global::Reqnroll.Table table241 = new global::Reqnroll.Table(new string[] {
                            "ClaimStatus",
                            "RepairCompletionDate",
                            "LaborCode"});
                table241.AddRow(new string[] {
                            "Certified",
                            "2024-05-10",
                            "LAB001"});
#line 35
 await testRunner.AndAsync("warranty claims:", ((string)(null)), table241, "And ");
#line hidden
#line 38
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 39
 await testRunner.ThenAsync("SSC \"SSC-001\" is marked as repaired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Warranty claim with non-matching status is ignored")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "Warranty claim with non-matching status is ignored")]
        public async global::System.Threading.Tasks.Task WarrantyClaimWithNon_MatchingStatusIsIgnored()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Warranty claim with non-matching status is ignored", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Repair detected via matching warranty claim", null, tagsOfRule);
#line 41
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table242 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1"});
                table242.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001"});
#line 42
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table242, "Given ");
#line hidden
                global::Reqnroll.Table table243 = new global::Reqnroll.Table(new string[] {
                            "ClaimStatus",
                            "RepairCompletionDate",
                            "DistributorComment"});
                table243.AddRow(new string[] {
                            "RejectedPermanently",
                            "2024-04-01",
                            "Repair for SSC-001"});
#line 45
 await testRunner.AndAsync("warranty claims:", ((string)(null)), table243, "And ");
#line hidden
#line 48
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 49
 await testRunner.ThenAsync("SSC \"SSC-001\" is marked as not repaired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="SSC repaired via labor line")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "SSC repaired via labor line")]
        public async global::System.Threading.Tasks.Task SSCRepairedViaLaborLine()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("SSC repaired via labor line", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Repair detected via matching labor line", null, tagsOfRule);
#line 53
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table244 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1"});
                table244.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001"});
#line 54
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table244, "Given ");
#line hidden
                global::Reqnroll.Table table245 = new global::Reqnroll.Table(new string[] {
                            "LaborCode",
                            "InvoiceDate",
                            "InvoiceStatus"});
                table245.AddRow(new string[] {
                            "LAB001",
                            "2024-06-01",
                            "X"});
#line 57
 await testRunner.AndAsync("labor lines:", ((string)(null)), table245, "And ");
#line hidden
#line 60
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 61
 await testRunner.ThenAsync("SSC \"SSC-001\" is marked as repaired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 62
 await testRunner.AndAsync("SSC \"SSC-001\" has repair date \"2024-06-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="SSC repaired via labor line with status C")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "SSC repaired via labor line with status C")]
        public async global::System.Threading.Tasks.Task SSCRepairedViaLaborLineWithStatusC()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("SSC repaired via labor line with status C", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Repair detected via matching labor line", null, tagsOfRule);
#line 64
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table246 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1"});
                table246.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001"});
#line 65
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table246, "Given ");
#line hidden
                global::Reqnroll.Table table247 = new global::Reqnroll.Table(new string[] {
                            "LaborCode",
                            "InvoiceDate",
                            "InvoiceStatus"});
                table247.AddRow(new string[] {
                            "LAB001",
                            "2024-07-01",
                            "C"});
#line 68
 await testRunner.AndAsync("labor lines:", ((string)(null)), table247, "And ");
#line hidden
#line 71
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 72
 await testRunner.ThenAsync("SSC \"SSC-001\" is marked as repaired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 73
 await testRunner.AndAsync("SSC \"SSC-001\" has repair date \"2024-07-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Labor line with non-matching status is ignored")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "Labor line with non-matching status is ignored")]
        public async global::System.Threading.Tasks.Task LaborLineWithNon_MatchingStatusIsIgnored()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Labor line with non-matching status is ignored", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Repair detected via matching labor line", null, tagsOfRule);
#line 75
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table248 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1"});
                table248.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001"});
#line 76
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table248, "Given ");
#line hidden
                global::Reqnroll.Table table249 = new global::Reqnroll.Table(new string[] {
                            "LaborCode",
                            "InvoiceDate",
                            "InvoiceStatus"});
                table249.AddRow(new string[] {
                            "LAB001",
                            "2024-06-01",
                            "O"});
#line 79
 await testRunner.AndAsync("labor lines:", ((string)(null)), table249, "And ");
#line hidden
#line 82
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 83
 await testRunner.ThenAsync("SSC \"SSC-001\" is marked as not repaired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="SSC not repaired when no evidence found")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "SSC not repaired when no evidence found")]
        public async global::System.Threading.Tasks.Task SSCNotRepairedWhenNoEvidenceFound()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("SSC not repaired when no evidence found", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("No repair evidence", null, tagsOfRule);
#line 87
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table250 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1"});
                table250.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001"});
#line 88
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table250, "Given ");
#line hidden
#line 91
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 92
 await testRunner.ThenAsync("SSC \"SSC-001\" is marked as not repaired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="No SSC records returns null")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "No SSC records returns null")]
        public async global::System.Threading.Tasks.Task NoSSCRecordsReturnsNull()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("No SSC records returns null", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("No repair evidence", null, tagsOfRule);
#line 94
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 95
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 96
 await testRunner.ThenAsync("there are no SSC records", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Multiple SSCs with mixed repair status")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "Multiple SSCs with mixed repair status")]
        public async global::System.Threading.Tasks.Task MultipleSSCsWithMixedRepairStatus()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Multiple SSCs with mixed repair status", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Result composition", null, tagsOfRule);
#line 100
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table251 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1",
                            "RepairDate"});
                table251.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001",
                            "2024-03-15"});
                table251.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-002",
                            "Seatbelt recall",
                            "LAB002",
                            ""});
#line 101
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table251, "Given ");
#line hidden
#line 105
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 106
 await testRunner.ThenAsync("SSC \"SSC-001\" is marked as repaired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 107
 await testRunner.AndAsync("SSC \"SSC-002\" is marked as not repaired", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="SSC parts and labor codes appear in result")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Vehicle Safety Service Campaigns (SSC)")]
        [global::Xunit.TraitAttribute("Description", "SSC parts and labor codes appear in result")]
        public async global::System.Threading.Tasks.Task SSCPartsAndLaborCodesAppearInResult()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("SSC parts and labor codes appear in result", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Result composition", null, tagsOfRule);
#line 109
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table252 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "CampaignCode",
                            "Description",
                            "LaborCode1",
                            "LaborCode2",
                            "PartNumber1",
                            "PartNumber2"});
                table252.AddRow(new string[] {
                            "1G1ZC5E17BF283048",
                            "SSC-001",
                            "Airbag recall",
                            "LAB001",
                            "LAB002",
                            "PRT001",
                            "PRT002"});
#line 110
 await testRunner.GivenAsync("SSC affected vehicles:", ((string)(null)), table252, "Given ");
#line hidden
#line 113
 await testRunner.WhenAsync("Checking \"1G1ZC5E17BF283048\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 114
 await testRunner.ThenAsync("SSC \"SSC-001\" has 2 labor codes", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 115
 await testRunner.AndAsync("SSC \"SSC-001\" has 2 part numbers", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
            {
                await VehicleSafetyServiceCampaignsSSCFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
            {
                await VehicleSafetyServiceCampaignsSSCFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
