// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace LookupServices.BDD.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class WarrantyAndFreeServiceDatesFeature : object, Xunit.IClassFixture<WarrantyAndFreeServiceDatesFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Xunit.ITestOutputHelper _testOutputHelper;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Warranty and Free Service Dates", @"  Warranty and free service start dates are determined by the vehicle's sale
  circumstances. The system checks service activation records, warranty activation
  dates, and invoice dates (in that priority order). Broker sales have separate
  logic. Date shifts can override calculated dates. Extended warranty entries
  are tracked independently.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "WarrantyDates.feature"
#line hidden
        
        public WarrantyAndFreeServiceDatesFeature(WarrantyAndFreeServiceDatesFeature.FixtureData fixtureData, Xunit.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/WarrantyDates.feature.ndjson", 11);
        }
        
        async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Warranty date from service activation")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Warranty and Free Service Dates")]
        [global::Xunit.TraitAttribute("Description", "Warranty date from service activation")]
        public async global::System.Threading.Tasks.Task WarrantyDateFromServiceActivation()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Warranty date from service activation", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 10
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table62 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "InvoiceDate"});
                table62.AddRow(new string[] {
                            "1FDKF37GXVEB34368",
                            "2024-01-15"});
#line 11
  await testRunner.GivenAsync("vehicles in dealer stock:", ((string)(null)), table62, "Given ");
#line hidden
                global::Reqnroll.Table table63 = new global::Reqnroll.Table(new string[] {
                            "WarrantyActivationDate",
                            "CompanyID"});
                table63.AddRow(new string[] {
                            "2024-02-01",
                            "1"});
#line 14
  await testRunner.AndAsync("vehicle service activations:", ((string)(null)), table63, "And ");
#line hidden
#line 17
  await testRunner.WhenAsync("evaluating warranty dates for \"1FDKF37GXVEB34368\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 18
  await testRunner.ThenAsync("the warranty start date is \"2024-02-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Warranty date falls back to vehicle warranty activation date")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Warranty and Free Service Dates")]
        [global::Xunit.TraitAttribute("Description", "Warranty date falls back to vehicle warranty activation date")]
        public async global::System.Threading.Tasks.Task WarrantyDateFallsBackToVehicleWarrantyActivationDate()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Warranty date falls back to vehicle warranty activation date", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 20
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table64 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "InvoiceDate",
                            "WarrantyActivationDate"});
                table64.AddRow(new string[] {
                            "1FDKF37GXVEB34368",
                            "2024-01-15",
                            "2024-01-20"});
#line 21
  await testRunner.GivenAsync("vehicles in dealer stock:", ((string)(null)), table64, "Given ");
#line hidden
#line 24
  await testRunner.WhenAsync("evaluating warranty dates for \"1FDKF37GXVEB34368\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 25
  await testRunner.ThenAsync("the warranty start date is \"2024-01-20\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Warranty date defaults to invoice date when enabled")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Warranty and Free Service Dates")]
        [global::Xunit.TraitAttribute("Description", "Warranty date defaults to invoice date when enabled")]
        public async global::System.Threading.Tasks.Task WarrantyDateDefaultsToInvoiceDateWhenEnabled()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Warranty date defaults to invoice date when enabled", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 27
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 28
  await testRunner.GivenAsync("warranty start date defaults to invoice date", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table65 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "InvoiceDate"});
                table65.AddRow(new string[] {
                            "1FDKF37GXVEB34368",
                            "2024-01-15"});
#line 29
  await testRunner.AndAsync("vehicles in dealer stock:", ((string)(null)), table65, "And ");
#line hidden
#line 32
  await testRunner.WhenAsync("evaluating warranty dates for \"1FDKF37GXVEB34368\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 33
  await testRunner.ThenAsync("the warranty start date is \"2024-01-15\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Warranty date is null when no activation and defaulting disabled")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Warranty and Free Service Dates")]
        [global::Xunit.TraitAttribute("Description", "Warranty date is null when no activation and defaulting disabled")]
        public async global::System.Threading.Tasks.Task WarrantyDateIsNullWhenNoActivationAndDefaultingDisabled()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Warranty date is null when no activation and defaulting disabled", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 35
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 36
  await testRunner.GivenAsync("warranty start date does not default to invoice date", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table66 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "InvoiceDate"});
                table66.AddRow(new string[] {
                            "1FDKF37GXVEB34368",
                            "2024-01-15"});
#line 37
  await testRunner.AndAsync("vehicles in dealer stock:", ((string)(null)), table66, "And ");
#line hidden
#line 40
  await testRunner.WhenAsync("evaluating warranty dates for \"1FDKF37GXVEB34368\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 41
  await testRunner.ThenAsync("the warranty start date is empty", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Default warranty period is 3 years")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Warranty and Free Service Dates")]
        [global::Xunit.TraitAttribute("Description", "Default warranty period is 3 years")]
        public async global::System.Threading.Tasks.Task DefaultWarrantyPeriodIs3Years()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Default warranty period is 3 years", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 45
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table67 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "InvoiceDate",
                            "BrandID"});
                table67.AddRow(new string[] {
                            "1FDKF37GXVEB34368",
                            "2024-01-15",
                            "1"});
#line 46
  await testRunner.GivenAsync("vehicles in dealer stock:", ((string)(null)), table67, "Given ");
#line hidden
                global::Reqnroll.Table table68 = new global::Reqnroll.Table(new string[] {
                            "WarrantyActivationDate",
                            "CompanyID"});
                table68.AddRow(new string[] {
                            "2024-02-01",
                            "1"});
#line 49
  await testRunner.AndAsync("vehicle service activations:", ((string)(null)), table68, "And ");
#line hidden
#line 52
  await testRunner.WhenAsync("evaluating warranty dates for \"1FDKF37GXVEB34368\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 53
  await testRunner.ThenAsync("the warranty end date is \"2027-02-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Brand-specific warranty period")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Warranty and Free Service Dates")]
        [global::Xunit.TraitAttribute("Description", "Brand-specific warranty period")]
        public async global::System.Threading.Tasks.Task Brand_SpecificWarrantyPeriod()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Brand-specific warranty period", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 55
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 56
  await testRunner.GivenAsync("brand 1 has a warranty period of 5 years", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table69 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "InvoiceDate",
                            "BrandID"});
                table69.AddRow(new string[] {
                            "1FDKF37GXVEB34368",
                            "2024-01-15",
                            "1"});
#line 57
  await testRunner.AndAsync("vehicles in dealer stock:", ((string)(null)), table69, "And ");
#line hidden
                global::Reqnroll.Table table70 = new global::Reqnroll.Table(new string[] {
                            "WarrantyActivationDate",
                            "CompanyID"});
                table70.AddRow(new string[] {
                            "2024-02-01",
                            "1"});
#line 60
  await testRunner.AndAsync("vehicle service activations:", ((string)(null)), table70, "And ");
#line hidden
#line 63
  await testRunner.WhenAsync("evaluating warranty dates for \"1FDKF37GXVEB34368\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 64
  await testRunner.ThenAsync("the warranty end date is \"2029-02-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Warranty date shift overrides calculated start date")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Warranty and Free Service Dates")]
        [global::Xunit.TraitAttribute("Description", "Warranty date shift overrides calculated start date")]
        public async global::System.Threading.Tasks.Task WarrantyDateShiftOverridesCalculatedStartDate()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Warranty date shift overrides calculated start date", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 68
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table71 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "InvoiceDate"});
                table71.AddRow(new string[] {
                            "1FDKF37GXVEB34368",
                            "2024-01-15"});
#line 69
  await testRunner.GivenAsync("vehicles in dealer stock:", ((string)(null)), table71, "Given ");
#line hidden
                global::Reqnroll.Table table72 = new global::Reqnroll.Table(new string[] {
                            "WarrantyActivationDate",
                            "CompanyID"});
                table72.AddRow(new string[] {
                            "2024-02-01",
                            "1"});
#line 72
  await testRunner.AndAsync("vehicle service activations:", ((string)(null)), table72, "And ");
#line hidden
                global::Reqnroll.Table table73 = new global::Reqnroll.Table(new string[] {
                            "NewDate"});
                table73.AddRow(new string[] {
                            "2023-06-01"});
#line 75
  await testRunner.AndAsync("warranty date shifts:", ((string)(null)), table73, "And ");
#line hidden
#line 78
  await testRunner.WhenAsync("evaluating warranty dates for \"1FDKF37GXVEB34368\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 79
  await testRunner.ThenAsync("the warranty start date is \"2023-06-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Free service date shift overrides free service start date")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Warranty and Free Service Dates")]
        [global::Xunit.TraitAttribute("Description", "Free service date shift overrides free service start date")]
        public async global::System.Threading.Tasks.Task FreeServiceDateShiftOverridesFreeServiceStartDate()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Free service date shift overrides free service start date", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 81
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table74 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "InvoiceDate"});
                table74.AddRow(new string[] {
                            "1FDKF37GXVEB34368",
                            "2024-01-15"});
#line 82
  await testRunner.GivenAsync("vehicles in dealer stock:", ((string)(null)), table74, "Given ");
#line hidden
                global::Reqnroll.Table table75 = new global::Reqnroll.Table(new string[] {
                            "WarrantyActivationDate",
                            "CompanyID"});
                table75.AddRow(new string[] {
                            "2024-02-01",
                            "1"});
#line 85
  await testRunner.AndAsync("vehicle service activations:", ((string)(null)), table75, "And ");
#line hidden
                global::Reqnroll.Table table76 = new global::Reqnroll.Table(new string[] {
                            "NewDate"});
                table76.AddRow(new string[] {
                            "2023-09-01"});
#line 88
  await testRunner.AndAsync("free service item date shifts:", ((string)(null)), table76, "And ");
#line hidden
#line 91
  await testRunner.WhenAsync("evaluating warranty dates for \"1FDKF37GXVEB34368\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 92
  await testRunner.ThenAsync("the free service start date is \"2023-09-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Extended warranty dates from entries")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Warranty and Free Service Dates")]
        [global::Xunit.TraitAttribute("Description", "Extended warranty dates from entries")]
        public async global::System.Threading.Tasks.Task ExtendedWarrantyDatesFromEntries()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Extended warranty dates from entries", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 96
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table77 = new global::Reqnroll.Table(new string[] {
                            "VIN",
                            "InvoiceDate"});
                table77.AddRow(new string[] {
                            "1FDKF37GXVEB34368",
                            "2024-01-15"});
#line 97
  await testRunner.GivenAsync("vehicles in dealer stock:", ((string)(null)), table77, "Given ");
#line hidden
                global::Reqnroll.Table table78 = new global::Reqnroll.Table(new string[] {
                            "WarrantyActivationDate",
                            "CompanyID"});
                table78.AddRow(new string[] {
                            "2024-02-01",
                            "1"});
#line 100
  await testRunner.AndAsync("vehicle service activations:", ((string)(null)), table78, "And ");
#line hidden
                global::Reqnroll.Table table79 = new global::Reqnroll.Table(new string[] {
                            "StartDate",
                            "EndDate"});
                table79.AddRow(new string[] {
                            "2027-02-01",
                            "2029-02-01"});
#line 103
  await testRunner.AndAsync("extended warranty entries:", ((string)(null)), table79, "And ");
#line hidden
#line 106
  await testRunner.WhenAsync("evaluating warranty dates for \"1FDKF37GXVEB34368\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 107
  await testRunner.ThenAsync("the extended warranty start date is \"2027-02-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 108
  await testRunner.AndAsync("the extended warranty end date is \"2029-02-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
            {
                await WarrantyAndFreeServiceDatesFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
            {
                await WarrantyAndFreeServiceDatesFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
