// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShiftSoftware.ADP.Surveys.Sample.API.Data;

#nullable disable

namespace ShiftSoftware.ADP.Surveys.Sample.API.Migrations
{
    [DbContext(typeof(DB))]
    partial class DBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShiftSoftware.ADP.Surveys.Data.Entities.BankQuestion", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<Guid>("BankEntryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BiColumn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("LastReplicationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSaveDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastSavedByUserID")
                        .HasColumnType("bigint");

                    b.Property<bool>("Locked")
                        .HasColumnType("bit");

                    b.Property<string>("QuestionJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Retired")
                        .HasColumnType("bit");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BankEntryID")
                        .IsUnique();

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("BankQuestion", "Surveys");

                    b.HasAnnotation("SqlServer:TemporalHistoryTableSchema", "Surveys");
                });

            modelBuilder.Entity("ShiftSoftware.ADP.Surveys.Data.Entities.ScreenTemplate", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("LastReplicationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSaveDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastSavedByUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("ScreenTemplate", "Surveys");

                    b.HasAnnotation("SqlServer:TemporalHistoryTableSchema", "Surveys");
                });

            modelBuilder.Entity("ShiftSoftware.ADP.Surveys.Data.Entities.Survey", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("DraftJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastReplicationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSaveDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastSavedByUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("PublishedVersionNumber")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("Survey", "Surveys");

                    b.HasAnnotation("SqlServer:TemporalHistoryTableSchema", "Surveys");
                });

            modelBuilder.Entity("ShiftSoftware.ADP.Surveys.Data.Entities.SurveyAnswer", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<Guid?>("BankEntryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KeyAtSubmission")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("LastReplicationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSaveDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastSavedByUserID")
                        .HasColumnType("bigint");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<long>("SurveyResponseID")
                        .HasColumnType("bigint");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BankEntryID");

                    b.HasIndex("KeyAtSubmission");

                    b.HasIndex("SurveyResponseID");

                    b.ToTable("SurveyAnswer", "Surveys");

                    b.HasAnnotation("SqlServer:TemporalHistoryTableSchema", "Surveys");
                });

            modelBuilder.Entity("ShiftSoftware.ADP.Surveys.Data.Entities.SurveyInstance", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("CustomerRef")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastReplicationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSaveDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastSavedByUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("MetaDataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PublicID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("SurveyID")
                        .HasColumnType("bigint");

                    b.Property<long>("SurveyVersionID")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("TriggeredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TriggeredBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CustomerRef");

                    b.HasIndex("PublicID")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("SurveyID");

                    b.HasIndex("SurveyVersionID");

                    b.ToTable("SurveyInstance", "Surveys");

                    b.HasAnnotation("SqlServer:TemporalHistoryTableSchema", "Surveys");
                });

            modelBuilder.Entity("ShiftSoftware.ADP.Surveys.Data.Entities.SurveyResponse", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("AgentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastReplicationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSaveDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastSavedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("SurveyInstanceID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("SurveyInstanceID");

                    b.ToTable("SurveyResponse", "Surveys");

                    b.HasAnnotation("SqlServer:TemporalHistoryTableSchema", "Surveys");
                });

            modelBuilder.Entity("ShiftSoftware.ADP.Surveys.Data.Entities.SurveyVersion", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastReplicationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSaveDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastSavedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ResolvedJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SurveyID")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Hash");

                    b.HasIndex("SurveyID", "Version")
                        .IsUnique();

                    b.ToTable("SurveyVersion", "Surveys");

                    b.HasAnnotation("SqlServer:TemporalHistoryTableSchema", "Surveys");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftEntity.EFCore.Entities.DeletedRowLog", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("LastReplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PartitionKeyLevelOneType")
                        .HasColumnType("int");

                    b.Property<string>("PartitionKeyLevelOneValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartitionKeyLevelThreeType")
                        .HasColumnType("int");

                    b.Property<string>("PartitionKeyLevelThreeValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartitionKeyLevelTwoType")
                        .HasColumnType("int");

                    b.Property<string>("PartitionKeyLevelTwoValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RowID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("ContainerName", "LastReplicationDate");

                    b.ToTable("DeletedRowLogs");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.AccessTree", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastReplicationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSaveDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastSavedByUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Tree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("AccessTrees", "ShiftIdentity");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.App", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AppSecret")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastReplicationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSaveDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastSavedByUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("ID");

                    b.HasIndex("AppId")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("Apps", "ShiftIdentity");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.Brand", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long?>("BrandID")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasComputedColumnSql("ID");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("IntegrationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastReplicationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSaveDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastSavedByUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Brands", "ShiftIdentity");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.City", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("bit");

                    b.Property<long?>("CityID")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasComputedColumnSql("ID");

                    b.Property<long?>("CountryID")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("IntegrationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastReplicationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSaveDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastSavedByUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RegionID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("RegionID");

                    b.ToTable("Cities", "ShiftIdentity");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.Company", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("bit");

                    b.Property<long?>("CompanyID")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasComputedColumnSql("ID");

                    b.Property<int>("CompanyType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("CustomFields")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("HQAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HQEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HQPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntegrationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastReplicationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSaveDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastSavedByUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("LegalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ParentCompanyID")
                        .HasColumnType("bigint");

                    b.Property<string>("ShortCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("ParentCompanyID");

                    b.ToTable("Companies", "ShiftIdentity");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.CompanyBranch", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("bit");

                    b.Property<long?>("CityID")
                        .HasColumnType("bigint");

                    b.Property<long?>("CompanyBranchID")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasComputedColumnSql("ID");

                    b.Property<long?>("CompanyID")
                        .HasColumnType("bigint");

                    b.Property<long?>("CountryID")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("CustomFields")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntegrationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastReplicationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSaveDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastSavedByUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobilePhotos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photos")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("PublishTargets")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RegionID")
                        .HasColumnType("bigint");

                    b.Property<string>("ShortCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkingDays")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkingHours")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CityID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("RegionID");

                    b.ToTable("CompanyBranches", "ShiftIdentity");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.CompanyBranchBrand", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long>("BrandID")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyBranchID")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastReplicationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSaveDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastSavedByUserID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("BrandID");

                    b.HasIndex("CompanyBranchID");

                    b.ToTable("CompanyBranchBrands", "ShiftIdentity");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.CompanyBranchDepartment", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long>("CompanyBranchID")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<long>("DepartmentID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastReplicationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSaveDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastSavedByUserID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("CompanyBranchID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("CompanyBranchDepartments", "ShiftIdentity");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.CompanyBranchService", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long>("CompanyBranchID")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastReplicationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSaveDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastSavedByUserID")
                        .HasColumnType("bigint");

                    b.Property<long>("ServiceID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("CompanyBranchID");

                    b.HasIndex("ServiceID");

                    b.ToTable("CompanyBranchServices", "ShiftIdentity");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.CompanyCalendar", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long?>("CompanyID")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntryType")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastReplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("LastSaveDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastSavedByUserID")
                        .HasColumnType("bigint");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("ShiftGroups")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeekendGroups")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("StartDate", "EndDate", "CompanyID", "IsDeleted");

                    b.ToTable("CompanyCalendars", "ShiftIdentity");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.CompanyCalendarBranch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyBranchID")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyCalendarID")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CompanyCalendarID");

                    b.ToTable("CompanyCalendarBranches", "ShiftIdentity");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.Country", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("bit");

                    b.Property<string>("CallingCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CountryID")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasComputedColumnSql("ID");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntegrationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastReplicationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSaveDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastSavedByUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DisplayOrder");

                    b.ToTable("Countries", "ShiftIdentity");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.Department", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("IntegrationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastReplicationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSaveDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastSavedByUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Departments", "ShiftIdentity");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.Region", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("bit");

                    b.Property<long?>("CountryID")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntegrationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastReplicationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSaveDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastSavedByUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RegionID")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasComputedColumnSql("ID");

                    b.Property<string>("ShortCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CountryID");

                    b.HasIndex("DisplayOrder");

                    b.ToTable("Regions", "ShiftIdentity");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.Service", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("IntegrationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastReplicationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSaveDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastSavedByUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Services", "ShiftIdentity");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.Team", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long?>("CompanyID")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("IntegrationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastReplicationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSaveDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastSavedByUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TeamID")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasComputedColumnSql("ID");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Teams", "ShiftIdentity");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.TeamCompanyBranch", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long>("CompanyBranchID")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastReplicationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSaveDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastSavedByUserID")
                        .HasColumnType("bigint");

                    b.Property<long>("TeamID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("CompanyBranchID");

                    b.HasIndex("TeamID");

                    b.ToTable("TeamBranches", "ShiftIdentity");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.TeamUser", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastReplicationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSaveDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastSavedByUserID")
                        .HasColumnType("bigint");

                    b.Property<long>("TeamID")
                        .HasColumnType("bigint");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("TeamID");

                    b.HasIndex("UserID");

                    b.ToTable("TeamUsers", "ShiftIdentity");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.User", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("AccessTree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("bit");

                    b.Property<long?>("CompanyBranchID")
                        .HasColumnType("bigint");

                    b.Property<long?>("CompanyID")
                        .HasColumnType("bigint");

                    b.Property<long?>("CountryID")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IntegrationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastReplicationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSaveDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastSavedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("LastSeen")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("LockDownUntil")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoginAttempts")
                        .HasColumnType("int");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("PhoneVerified")
                        .HasColumnType("bit");

                    b.Property<long?>("RegionID")
                        .HasColumnType("bigint");

                    b.Property<bool>("RequireChangePassword")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("VerificationSASToken")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CompanyBranchID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("CountryID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0 AND Email is not null");

                    b.HasIndex("IntegrationId")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0 AND IntegrationId is not null");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0 AND Phone is not null");

                    b.HasIndex("RegionID");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("Users", "ShiftIdentity");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.UserAccessTree", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long>("AccessTreeID")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastReplicationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSaveDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastSavedByUserID")
                        .HasColumnType("bigint");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("AccessTreeID");

                    b.HasIndex("UserID");

                    b.ToTable("UserAccessTrees", "ShiftIdentity");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.UserLog", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CreatedByUserID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastReplicationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSaveDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastSavedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("LastSeen")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("UserLogs", "ShiftIdentity");
                });

            modelBuilder.Entity("ShiftSoftware.ADP.Surveys.Data.Entities.SurveyAnswer", b =>
                {
                    b.HasOne("ShiftSoftware.ADP.Surveys.Data.Entities.BankQuestion", "BankQuestion")
                        .WithMany("Answers")
                        .HasForeignKey("BankEntryID")
                        .HasPrincipalKey("BankEntryID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ShiftSoftware.ADP.Surveys.Data.Entities.SurveyResponse", "SurveyResponse")
                        .WithMany("Answers")
                        .HasForeignKey("SurveyResponseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BankQuestion");

                    b.Navigation("SurveyResponse");
                });

            modelBuilder.Entity("ShiftSoftware.ADP.Surveys.Data.Entities.SurveyInstance", b =>
                {
                    b.HasOne("ShiftSoftware.ADP.Surveys.Data.Entities.Survey", "Survey")
                        .WithMany("Instances")
                        .HasForeignKey("SurveyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShiftSoftware.ADP.Surveys.Data.Entities.SurveyVersion", "SurveyVersion")
                        .WithMany("Instances")
                        .HasForeignKey("SurveyVersionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Survey");

                    b.Navigation("SurveyVersion");
                });

            modelBuilder.Entity("ShiftSoftware.ADP.Surveys.Data.Entities.SurveyResponse", b =>
                {
                    b.HasOne("ShiftSoftware.ADP.Surveys.Data.Entities.SurveyInstance", "SurveyInstance")
                        .WithMany("Responses")
                        .HasForeignKey("SurveyInstanceID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SurveyInstance");
                });

            modelBuilder.Entity("ShiftSoftware.ADP.Surveys.Data.Entities.SurveyVersion", b =>
                {
                    b.HasOne("ShiftSoftware.ADP.Surveys.Data.Entities.Survey", "Survey")
                        .WithMany("Versions")
                        .HasForeignKey("SurveyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.City", b =>
                {
                    b.HasOne("ShiftSoftware.ShiftIdentity.Core.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionID");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.Company", b =>
                {
                    b.HasOne("ShiftSoftware.ShiftIdentity.Core.Entities.Company", "ParentCompany")
                        .WithMany("ChildCompanies")
                        .HasForeignKey("ParentCompanyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCompany");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.CompanyBranch", b =>
                {
                    b.HasOne("ShiftSoftware.ShiftIdentity.Core.Entities.City", "City")
                        .WithMany("CompanyBranches")
                        .HasForeignKey("CityID");

                    b.HasOne("ShiftSoftware.ShiftIdentity.Core.Entities.Company", "Company")
                        .WithMany("CompanyBranches")
                        .HasForeignKey("CompanyID");

                    b.HasOne("ShiftSoftware.ShiftIdentity.Core.Entities.Region", "Region")
                        .WithMany("CompanyBranches")
                        .HasForeignKey("RegionID");

                    b.Navigation("City");

                    b.Navigation("Company");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.CompanyBranchBrand", b =>
                {
                    b.HasOne("ShiftSoftware.ShiftIdentity.Core.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShiftSoftware.ShiftIdentity.Core.Entities.CompanyBranch", "CompanyBranch")
                        .WithMany("CompanyBranchBrands")
                        .HasForeignKey("CompanyBranchID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("CompanyBranch");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.CompanyBranchDepartment", b =>
                {
                    b.HasOne("ShiftSoftware.ShiftIdentity.Core.Entities.CompanyBranch", "CompanyBranch")
                        .WithMany("CompanyBranchDepartments")
                        .HasForeignKey("CompanyBranchID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShiftSoftware.ShiftIdentity.Core.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyBranch");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.CompanyBranchService", b =>
                {
                    b.HasOne("ShiftSoftware.ShiftIdentity.Core.Entities.CompanyBranch", "CompanyBranch")
                        .WithMany("CompanyBranchServices")
                        .HasForeignKey("CompanyBranchID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShiftSoftware.ShiftIdentity.Core.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyBranch");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.CompanyCalendarBranch", b =>
                {
                    b.HasOne("ShiftSoftware.ShiftIdentity.Core.Entities.CompanyCalendar", "CompanyCalendar")
                        .WithMany("Branches")
                        .HasForeignKey("CompanyCalendarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyCalendar");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.Region", b =>
                {
                    b.HasOne("ShiftSoftware.ShiftIdentity.Core.Entities.Country", "Country")
                        .WithMany("Regions")
                        .HasForeignKey("CountryID");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.Team", b =>
                {
                    b.HasOne("ShiftSoftware.ShiftIdentity.Core.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.TeamCompanyBranch", b =>
                {
                    b.HasOne("ShiftSoftware.ShiftIdentity.Core.Entities.CompanyBranch", "CompanyBranch")
                        .WithMany()
                        .HasForeignKey("CompanyBranchID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShiftSoftware.ShiftIdentity.Core.Entities.Team", "Team")
                        .WithMany("TeamCompanyBranches")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyBranch");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.TeamUser", b =>
                {
                    b.HasOne("ShiftSoftware.ShiftIdentity.Core.Entities.Team", "Team")
                        .WithMany("TeamUsers")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShiftSoftware.ShiftIdentity.Core.Entities.User", "User")
                        .WithMany("TeamUsers")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.User", b =>
                {
                    b.HasOne("ShiftSoftware.ShiftIdentity.Core.Entities.CompanyBranch", "CompanyBranch")
                        .WithMany("Users")
                        .HasForeignKey("CompanyBranchID");

                    b.HasOne("ShiftSoftware.ShiftIdentity.Core.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID");

                    b.HasOne("ShiftSoftware.ShiftIdentity.Core.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryID");

                    b.HasOne("ShiftSoftware.ShiftIdentity.Core.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionID");

                    b.Navigation("Company");

                    b.Navigation("CompanyBranch");

                    b.Navigation("Country");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.UserAccessTree", b =>
                {
                    b.HasOne("ShiftSoftware.ShiftIdentity.Core.Entities.AccessTree", "AccessTree")
                        .WithMany()
                        .HasForeignKey("AccessTreeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShiftSoftware.ShiftIdentity.Core.Entities.User", "User")
                        .WithMany("AccessTrees")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccessTree");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.UserLog", b =>
                {
                    b.HasOne("ShiftSoftware.ShiftIdentity.Core.Entities.User", "User")
                        .WithOne("UserLog")
                        .HasForeignKey("ShiftSoftware.ShiftIdentity.Core.Entities.UserLog", "UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShiftSoftware.ADP.Surveys.Data.Entities.BankQuestion", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("ShiftSoftware.ADP.Surveys.Data.Entities.Survey", b =>
                {
                    b.Navigation("Instances");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("ShiftSoftware.ADP.Surveys.Data.Entities.SurveyInstance", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("ShiftSoftware.ADP.Surveys.Data.Entities.SurveyResponse", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("ShiftSoftware.ADP.Surveys.Data.Entities.SurveyVersion", b =>
                {
                    b.Navigation("Instances");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.City", b =>
                {
                    b.Navigation("CompanyBranches");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.Company", b =>
                {
                    b.Navigation("ChildCompanies");

                    b.Navigation("CompanyBranches");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.CompanyBranch", b =>
                {
                    b.Navigation("CompanyBranchBrands");

                    b.Navigation("CompanyBranchDepartments");

                    b.Navigation("CompanyBranchServices");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.CompanyCalendar", b =>
                {
                    b.Navigation("Branches");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.Country", b =>
                {
                    b.Navigation("Regions");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.Region", b =>
                {
                    b.Navigation("CompanyBranches");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.Team", b =>
                {
                    b.Navigation("TeamCompanyBranches");

                    b.Navigation("TeamUsers");
                });

            modelBuilder.Entity("ShiftSoftware.ShiftIdentity.Core.Entities.User", b =>
                {
                    b.Navigation("AccessTrees");

                    b.Navigation("TeamUsers");

                    b.Navigation("UserLog")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
